### ISSUE TITLE
Avoid parse command for config

### ISSUE THREAD

**Issue by albfan** [albfan/ag.vim#10]
commands starting with l means location list, ending with -g File search. Avoid that use a real flag config mechanishm

**Comment by albfan** [comment]
https://github.com/albfan/ag.vim/tree/wip-refactor

just comments and few naive options by now

**Comment by amerlyq** [comment]
Already replaced by symmetrical problem and discussion moved into #30.
Please, highlight your main ideas wip-refactor, yet not integrated into master, and remove that branch.

**Comment by albfan** [comment]
All pass by using dict objects (as recent work on `aggroup` fixes branch. Populate and object with all the config and reuse all around. As change seems nasty from your comments on aggroup branch I'm rebasing and resolving in a different way (reusing g:ag.last) Let's see if that's work for you and then this can be confronted and closed.

**Comment by albfan** [comment]
Almost all implemented. Let's close this
