### ISSUE TITLE
Searching from project root fails

### ISSUE THREAD

**Issue by letorbi** [albfan/ag.vim#107]
when I configure ag.vim to always start searching from the project root with:

```
let g:ag.working_path_mode="r"
```

I always get the following error when I start a search:

```
E119: Not enough arguments for function: s:exists                               
E15: Invalid expression: s:exists(_.'/'.m) | return m | endif
```

The problem seem to be in [line 29 of /autoload/ag/paths.vim](https://github.com/albfan/ag.vim/blob/master/autoload/ag/paths.vim#L29)

**Comment by albfan** [comment]
Can you describe your environment?

- OS version 
- vim version

if you can share a project to check with (a complete use case) would be nice

**Comment by letorbi** [comment]
I use Arch Linux with the neovim 0.3.1-1 package. I've tested it with my [Tarp.require repo](https://github.com/letorbi/tarp.require), which is hosted here on GitHub.

**Comment by albfan** [comment]
I have to add:

    let g:ag = {}

But was able to reproduce and fix, thanks for reporting

**Comment by letorbi** [comment]
Thanks for the fast fix, but unfortunately it is still not working. The syntax errors are all gone now, but opening a file from the results list fails, when the currently open file is not in the project-root.

In the [Tarp.require repo](https://github.com/letorbi/tarp.require) for example (*repo/* is the project root):

* The file *repo/test/index.js* is open
* I search: `:Ag require`
* I select the first result (`require.js|22 col31| ...`) and press enter
* Vim tries to open *repo/test/require.js* and fails

The correct file would have been *repo/require.js*. It seems that ag.vim adds a relative path to the path of the currently open file, while it should add it to the project root.
