### ISSUE TITLE
Opening a file from project-root fails

### ISSUE THREAD

**Issue by letorbi** [albfan/ag.vim#109]
Thanks for the fast fix of the searching from project-root (#107), but unfortunately the project-root option is still not working as expected. The syntax errors are all gone now, but opening a file from the results list fails, when the currently open file is not in the project-root.

In the [Tarp.require repo](https://github.com/letorbi/tarp.require) for example (*repo/* is the project-root):

* The file *repo/test/index.js* is open
* I search: `:Ag require`
* I select the first result `require.js|22 col31| ...` and press enter
* Vim tries to open *repo/test/require.js* and fails

The correct file would have been *repo/require.js*. It seems that ag.vim adds the relative path of the search result to the path of the currently open file, while it should add it to the project-root.

I still use Arch Linux with the neovim 0.3.1-1 package.

**Comment by albfan** [comment]
Let me check it.I will do a couple of test to fix this

**Comment by albfan** [comment]
I can't make it fail

![ag vim-searching-from-root](https://user-images.githubusercontent.com/220968/45800909-9c764f80-bcb2-11e8-8e9f-c36466d249b3.gif)

Are you sure you updated the plugin to lastest version. See I detect another bug (not related with this, but is worth to update anyway) Please close this if it works for you

**Comment by letorbi** [comment]
I've updated the plugin to the latest version (9fb460e) , cleared my .vimrc and tried Neovim and Vim. Always the same result - it is not working (see video).

![ag-vim](https://user-images.githubusercontent.com/1268015/45974763-a3021f80-c042-11e8-8ce2-4f38d309cb13.gif)

The video should show exactly the flow I described in my previous comment to reproduce the error.

Here is also the contents of my .vimrc:

```
call plug#begin('~/.vim/plugged')
Plug 'albfan/ag.vim'
call plug#end()
let g:ag = {} 
let g:ag.working_path_mode='r'
set statusline+=%F\ %m%r%=%l\/%L
```

**Comment by letorbi** [comment]
The reason why it works in your video could be that you open the file via `nvim tarp.require/test/index.js`. Can open the file via `nvim ./index.js` and try again? This should fail.

**Comment by albfan** [comment]
I was able to reproduce

The problem is here: https://github.com/albfan/ag.vim/blob/master/autoload/ag/ctrl.vim#L187

the search from ag is relative to detected root path, but open command is using current file path

Will fix soon

**Comment by albfan** [comment]
Feel free to reopen if this do not fix it for you

**Comment by albfan** [comment]
Close this if that solve your issue. Thanks for reporting!

**Comment by letorbi** [comment]
It's fixed. Thank you :)
