### ISSUE TITLE
Silently changing directory

### ISSUE THREAD

**Issue by amadanmath** [albfan/ag.vim#110]
`working_path_mode='r'` mode is silently changing the directory, which I believe to be against user expectations (certainly was against mine :D ).

I see that you preserve the `cwd_old`, but then do nothing with it, telling me you also probably thought the same, at at least one point.

I propose adding `lcd -` just after [the `call` line](https://github.com/albfan/ag.vim/blob/4f93ffa68dd50ae3ad4755eb98efa58693435abd/autoload/ag/bind.vim#L23) inside the `finally` clause; with `lcd -` (`lcd` with minus argument), there's no need to remember `cwd_old`:

```
function! s:lcd(f, varg)
  let l:cwd = ag#paths#pjroot('nearest')
  try
    exe "lcd ".l:cwd
  catch
    echom 'Failed to change directory to:'.l:cwd
  finally
    let _ = call(a:f, a:varg)
    lcd -
  endtry
  return _
endfunction
```

**Comment by albfan** [comment]
Certainly, there're problems with that, if you can submit a PR I would definitely merge it

**Comment by albfan** [comment]
A way to show how this should work. Is to mimic the root mode:

for a project:

```
doc/
   help.txt
src/
   main.c
tests/
   test1.c
meson.build
```

Lets say main.c contains a function called my_function. If you cd into doc directory, and open vim

    :AgGroup my_function

do not show results, but

    :AgGroupFile .. my_function

will show

    ../src/main.c:10:9 private void my_function () {

So basically `s:lcd` is a wrong implementation. Have to check in other ag.vim commands `:Ag` and provide a definitive solution. where root mode only change the path used in ag.

**Comment by albfan** [comment]
Update to master (fc6cf84) and let me know if this is fixed for you.

Taking the last example:

    :Ag my_function

and

    :AgGroup my_function

both works as described

**Comment by albfan** [comment]
Let me know if you need anything else, I see this as done.
