### ISSUE TITLE
Merging with rking (workflow)

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#21]
Do you plan to merge your undoubtedly fascinating additions into current trunk of rking, or continue to maintain this work as separate fork? If latter, could you please update your repo by merging with rking?

**Comment by albfan** [comment]
I tried so hard. For me this fork is basic for developing and I try to share from the beginning. But we are stuck on this pull request so long ago.

https://github.com/rking/ag.vim/pull/87

Basic problems are common behaviour (shortcuts and use of preview window)

Really don't mind if you keep on working on that pull request or rebase, or whatever workflow you prefer. I promise to provide as many help as I can. Feel free to propose here changes to be more upstream compatible in order to propose a PR accepted by @rking

**Comment by amerlyq** [comment]
As for diversity in shortcuts -- could you please rewrite them through intermediate `<Plug>` mappings with guards (like in [vim-sneak](https://github.com/justinmk/vim-sneak/blob/master/plugin/sneak.vim)), so user could configure mappings himself through some global dictionary extended by default one (e.g. see [mine](https://github.com/amerlyq/airy/blob/master/cfg/term/vim/after/ftplugin/qf.vim), but assume `<Plug>(ag-...)` in right parts)? You could have insight in [incsearch.vim](https://github.com/haya14busa/incsearch.vim) on how to dot this -- at least scan through doc for resulting configuration example.

As for preview window -- it must be optional, doesn't it? Why there are problems?

**Comment by albfan** [comment]
Of course here there is a naive shorcut implementation. Flexible and configurable shortcuts are desired so let's work on that

**Comment by amerlyq** [comment]
Found even better variant of remap using intermidiate `<SID>` maps in addition to `<Plug>` inside [NrrwRgn](https://github.com/chrisbra/NrrwRgn/blob/master/plugin/NrrwRgn.vim#L75).

**Comment by amerlyq** [comment]
You [suggested](https://github.com/rking/ag.vim/pull/87#issuecomment-158754188) to close PR and split it into several smaller and isolated PR (supposedly on separate feature-branches). How you would like to accomplish this? I could take part in cherry-picking and completion (like introduction of `<Plug>` mappings) on separate PR, but I don't think it would be possible to mark them as originally yours when doing PR. 

If I introduce roundabout pieces of code for mappings, etc... somewhat deprecating yours, and then you could separate, refine and propose `AgGroup` on top of them by yourself -- what do you think about it?

**Comment by albfan** [comment]
I have added you as collaborator from this repo. Let me know if you have any problems or lack of permissions.

I have closed former PR.Now we need to do several things. Let me know if I take too much detail:
- clone this repo
  
  ```
  $ git clone git@github.com:albfan/ag.vim.git
  ```
- add ag.vim as upstream remote
  
  ```
  $ git remote add upstream https://github.com/rking/ag.vim
  ```
- try a simple rebase
  
  ```
  $ git checkout -b rebase master 
  $ git rebase upstream/master rebase
  ```
  
  fix problems, hack, hack, hack, bla bla bla.
  
  ```
  $ git pull origin rebase
  ```
  
  See where we are (all working, nothing working, impossible to merge)
- Whether this works or not, cover project with test cases, I will add a CI on travis
  
  https://travis-ci.org/albfan/ag.vim
  
  Here we can add any supposed working feature or request failed to ease testing implementations.

Let me know if you need any tip or guide.

**Comment by amerlyq** [comment]
I tried to rebase and it was too bad to be good:)
Besides, it will be splitted anyway, so cherry-picking from the start is better.
Some commits are already deprecated. And incrementally rebasing them is pain.
_(As cherry-pick for some commits will not work, sorry, if I couldn't kept your commit id for them.)_

What I propose now (and will do) is next (edited#8): 
**NOTE:** rebasing/deleting involves history rewriting and all local copies after `push` become `out of sync` so need to be re-cloned again.
- move  all your commits into separate `dev_aggroup` branch to preserv your work
- revert your master and sync it with rking
- create feature-branches on base of this synced master -- all of them from same `master/HEAD`
- isolate and distribute yours/mine changes between those feature-branches
- make tests and travis as separate dependent feature-branches
- squash all rejected/overwritten changes in FB before merging anywhere
- use `master` as main dev branch and merge all FB into it periodically for CI with travis
- rebase/merge `master` with `rking/ag.vim/master` when PR accepted, delete corresponding FB.
- all complete features, with PR yet not merged, rebased on `rking/ag.vim/master` separately
- all new features in progress are branched from last `master`; after things done, branch is rebased onto last `rking/ag.vim/master` and merged back into `master` for testing with CI, then sent to rking for PR.
- when all old features from `dev_aggroup` will be distributed, delete `dev_aggroup` branch.

This workflow will allow us to keep development on edge and propose atomic PR for rking.
You could instigate individual pull-requests for each of them, when our disagreements on implementation will be eliminated:) After PRs will be merged, you can delete those feature-branches (at least their labels), retaining clean branch list.

**Comment by albfan** [comment]
All sounds good. Just a comment. As fork albfan/ag.vim is expected to have a tip on its own changes. Here upstream/master is a branch different from master, as in rking/ag.vim our PR will be branches.

In albfan/ag.vim/master will be all features we judge correctly. Cherry picking or splitting or squashing for PR on different branches. master never will be eligible for PR. Master is expected to be rebased on accepted PR from time to time as is the tip from a fork

**Comment by amerlyq** [comment]
Ah, my bad, I forgot we work inside fork to propose changes and not in main repo:)
Then, there is no need to create `integration` branch, as all our FB
will be reasonably merged into your master.
I will edit plot in one-two hours using PC (done!).

I suppose, you understand, that isolation of your changes in separate
branch and reverting master to prepare merging of FB requires rewriting
history in git? Therefore your local clone will become broken and you 
need to re-clone it cleanly. (added note in plot!)
Are you agreed with this?

**Comment by amerlyq** [comment]
Fixed plot till `beta#8` :D

Reports for current progress and made decisions about your commits I will place in this issue, because them aren't introducing new changes and dealing with merging. 
Ask you to do the same thing, when you will be extracting AgGroup-related stuff.
For all new added/replaced code I will create issues, as you asked.

**Comment by amerlyq** [comment]
All independent changes to ag.vim trunk code are isolated into separate branches `fix_...`. 
All exceptionally yours code I'm placing into `feature_AgGroupe` branch.
Please, revise it, squash/rewrite some commits, as them are somewhat messy for review.
You will not break mine copy by rewriting history until you work in this separate branch.
Also, think if it would have sense to split this branch in multiple chained FB -- like AgGroup, AgGroupFile, syntax highlight, buffer mapping (however I think separate set of mappings is bad).

For test I chose separate branch `QA_AgGroup`, because their usage can be rejected at the end separately (like the case, when maintainer don't like that particular testsuit). But we could continue use them. Using travis without testsuit has no sense at all, therefore it will be branched from this branch to allow chained PRs -- for test suit, and only if it approved -- for travis.

As for mapping -- your code will be substituted by my `feature_mappings` general enhancements.
And then separated into `feature_AgGroupe_mappings` with new API used.

After all this work will be accepted, as your code has somewhat large additions, I think it would be nice to separate code into `autoload/ag/ag.vim` and `autoload/ag/group.vim`

**Comment by amerlyq** [comment]
Things left to do:
- [ ] Replace all your shortcuts inside `feature_AgGroup_mappings` by new API when ready, squash all deprecated then.
- [ ] Extract "Shell mimic" description from `demo_AgGroup` README (you messed up two purposes in one commit) and move it into `feature_AgGroup`.
- [ ] Move from `feature_AgGroup` all related stuff into `feature_AgGroup_cmd`, `feature_buffer_mappings` and `feature_buffer_syntax`.
- [ ] Think if you could extend default ag mappings instead of your own set.
- [ ] Forced smart-case merged in respect to next commits workability, but need to rewrite it to be able to force '-i' on it.
- [ ] Do something with `origin/wip-refactor`
- [ ] Merge all branches into master, when they are refactored.

You will need to split some of your commits manually. Procedure is next:

``` bash
git cherry-pick --no-commit #hash
git reset
git add --patch ag.vim
# then choose necessary hunks to create separate commit (see its help)
git commit -am "agcommand"
git add --patch ag.vim
# repeat for other parts of file
git commit -am "syntax"
git checkout HEAD  # drop changes back
```

Then as usual -- create branches and cherry-pick into them those separated commits.

``` bash
git checkout master
git branch #name && git checkout #name
git cherry-pick #hash_syntax
# repeat
```

**Comment by amerlyq** [comment]
I hope you read my messages once in time on web and not always through mail, because I edit them rather often until you respond.
Final changelog: 

```
feature_AgGroup_mappings
    * 2015-11-28 Fix configurable shortcuts deactivation (HEAD -> dev_aggroup, origin/master, origin/HEAD) [albfan] :7838e18
QA_AgGroup
    * 2015-11-28 Add testsuite [albfan] :e315fba
feature_AgGroup
    * 2015-11-28 Capture highlight errors on complex searches [albfan] :7ac2f71
    * 2015-11-21 default shortcuts for normal and visual mode [albfan] :7828ef3
    * 2015-09-09 Toggle linenumber visualization [albfan] :3435c98
    * 2015-09-09 delete results [albfan] :83cec65
feature_AgGroup,  feature_AgGroup_mappings
    * 2015-09-08 Shorcut improvements [albfan] :dcb2788
feature_AgGroup_mappings
    * 2015-09-08 Allow to disable default shorcuts [albfan] :5b08d4f
feature_AgGroup
    * 2015-09-08 Respect smartcase for highlight [albfan] :211a09f
    * 2015-09-08 Force smartcase [albfan] :ce106ae
    * 2015-09-05 Explicit selection mode [albfan] :46891e4
feature_AgGroup_mappings
    * 2015-09-05 mappings for normal and visual mode [albfan] :832faaf
feature_AgGroup
    * 2015-09-05 Add AgGroupFile command [albfan] :8148060
|* 2015-08-30 config case sensitivity (origin/wip-refactor) [albfan] :86359eb
|* 2015-08-30 WIP replace with flags [albfan] :b17ba80
feature_AgGroup
    * 2015-08-30 Navigate to exact line [albfan] :4f19de0
    * 2015-07-20 highlight for regexp [albfan] :49189c5
    * 2015-07-20 use ag config for executable [albfan] :2297da5
fix_regressions
    * 2015-07-06 simplify logic [albfan] :eb151d1
feature_AgGroup
    * 2015-07-06 fix visual search [albfan] :d3b5731
fix_regressions
    * 2015-07-05 remove nosense code [albfan] :d5a3f77
Already implemented -- see issue [rking/ag.vim#100]
    * 2015-07-05 detect ag version > 0.25 [albfan] :c0c4cdd
feature_AgGroup
    * 2015-05-24 smart search selection [albfan] :60f3085
    * 2015-05-10 add space as result navigator [albfan] :328260f
    * 2015-05-10 open in appropriate window [albfan] :7a5f619
    * 2015-05-10 force unfold of selected line [albfan] :1477cca
    * 2015-05-10 variable refactor [albfan] :8745c94
    * 2015-05-10 use quickfix window [albfan] :e813f40
    * 2015-05-10 silent read [albfan] :9f6e0c7
    * 2015-02-14 avoid file completion for search # or 0% [albfan] :8a1e08b
QA_AgGroup
    * 2015-02-14 test failed about searching using # or 0% [albfan] :18228c4
feature_AgGroup
    * 2015-02-08 search with / [albfan] :f18fa4f
    * 2015-01-31 correct syn match for multiword search [albfan] :eb186c2
QA_AgGroup
    * 2015-01-31 add test cases [albfan] :2c69777
demo_AgGroup -- could be regected (binary resource) / better placed in orphaned branch?
    * 2015-01-27 Demonstration of AgGroup [albfan] :64c03db
feature_AgGroup
    * 2015-01-26 add AgGroup command [albfan] :a0f73da

```

**Comment by amerlyq** [comment]
Alright, all my changes are pushed with force. Back-up you repo for incidents and clone again:)
When your review my changes and affirm all your commits was moved into corresponding branches -- please, delete obsolete `dev_aggroup` branch.

``` bash
git branch -d dev_aggroup
git push origin :dev_aggroup
```

**Comment by albfan** [comment]
Great, work. In a couple of rounds we will have workflow defined.

By now I have to undo mostly all your work. See why:

https://github.com/junegunn/vader.vim/pull/61/files#r46087649

ag.vim fork has it's own life, and using it's dependencies (as vader plugin) generates it's own contributions. Showing this exactly problem to @junegunn would be annoying if he doesn't find pointed files on master for a quick try.

Remember, master will be untouched here. I have added and upstream branch here just to notice you it's not needed. On your local repo you should have a remote named upstream with rking repo, so you can see difference with upstream, but having it here just forces you to keep an outdated upstream head (as long as you didn't know the next push from rking) I will removed it in a few days.

About rewriting history a few tips:
- rely on `rebase --interactive` to do that work
  
  $ git checkout master
  $ git checkout -b myrebase
  $ git rebase -i upstream myrebase
  
  At this point you have all commits you need to reload on top of rking repo. You can squash all and then
  
    $ git reset HEAD^
  
  I have rebased my work on top of rking without problems using:
  
    $ git checkout master
    $ git checkout -b rebase
    $ git rebase upstream/master
  
  just need to resolve conflicts two times on autoload/ag.vim. This is expected as AgGroup is just new functionality, conflicts should be minor as it was.
  
  Here is results:
  
  https://github.com/albfan/ag.vim/tree/rebase
  
  For convenience I pushed 
  
  https://github.com/albfan/ag.vim/tree/rebase-squash
  
  From here we sould extract suggestions to rking repo.
  
  Use my git config files to realize where you are on the repo with:
  - https://github.com/albfan/dotfiles/blob/master/gitconfig#L11
  - https://github.com/albfan/dotfiles/blob/master/gitconfig#L26 
  
  e.g:
  
    $ git logg
    $ git logga
    $ git loggsa
  
  Notice I have silently correct some fails on testsuite:
  - https://github.com/albfan/ag.vim/blob/master/.travis.yml#L7
  - https://github.com/albfan/ag.vim/blob/master/.travis.yml#L9
  - https://github.com/albfan/ag.vim/blob/master/t/suite.sh#L44
  - https://github.com/albfan/ag.vim/blob/master/t/suite.sh#L96

About delete branches, Didn't you have permissions to do that?

**Comment by amerlyq** [comment]
Ah, it was incomplete work.
All those splitted branches need to merge back into your master, which I planned after your respond about completeness of my work.
Then `master` state will become the same as before. 
Do your really need to undo this splitting if you can continue refer to master that way and point it out in issues? Splitting was necessary to eliminate direct commits to master and replace workflow to  feature-branches. So all contributions could progress isolated and be used as separate PRs.

I doubt that working directly on master and than cherry-picking only when you want to send PR is fruitful. It's additional labour which prevents from easy contributing. Therefore master state _will be_ untouched -- as result of all merged feature-branches. But I see no reasons in keeping it having _the same history_ as before, as it messes up future development.

About deleting branch -- of course I can, but you must review my work.
This deletion couldn't be undone. And it's your's own work anyway...

You rewinded all I've done unconditionally... I'm a little sad...

**Comment by amerlyq** [comment]
Could you please do something with your `rebase` and `rebase-squashed` branches, that you created instead?
If I understand correctly, changes from them wasn't introduced into your master.
So if you could rebase and merge them into current master (and delete completely, of course) it would be great. Because them will conflict with future merging of #25 anyway and better to resolve this earlier.

**Comment by albfan** [comment]
rebase branch is all my work bumped on rking tip. You should take that as master (rebasing or merging your previous work on it). 

Don't worry I will rebase your work on top of it and you will have this repo ready to send PR. Do you see now why I want a test suite? Beyond my knowlegde and understanding of your changes, tests are the right way to check all your work perform as expected. Untested code worths nothing.

Meanwhile keep working on actual master, I will notice you

**Comment by amerlyq** [comment]
I know. It's simply too much to code from beginning with unknown testsuite.
I have already pushed many changes, therefore I will cover previous/new code with tests.
Treat that as prototyping until architecture mostly became clarified and when my investigation of new testsuit with adding appropriate tests results in less labour than bugfixing:)
(Edit) Exactly by that reason I started to refactor `suite.sh` some time ago.

Don't understand, though, what you mean by 'take rebase as master'.
You are using `rebase` branch completely for PR?
Or propose me to commit only in rebase branch and don't merge features in master?

(Edit) I noticed you said nothing about merging rebase into your master -- the reason original question was asked.

**Comment by albfan** [comment]
I fork rking on january. On rebase branch there are all those commits upon lastest rking changes. 

Working on it there will be no need to merge, but seeing the conflicts I needed to solve that can be done again from master.

**Comment by amerlyq** [comment]
Alright. I'm working on master until you notify. 
And you are managing this stuff with goal I don't comprehend even after explanation.
Maybe when you do what you want to do I will at least understand.

Until that, please, make a note on workflow what would you liked to do with my merged feature-branches?
- I delete them myself right after merging by `git branch -d FB && git push origin :FB`.
- They kept active after merge, until we decide in issue thread to close (is there some sense?) -- so branches can be active until decision even when issue closed.
- They kept alive until merge into upstream (but we will need to squash/split FB anyway!).

**Comment by albfan** [comment]
I have deleted `rebase-squashed` and `rebase` branches. I have created aggroup instead, cherry-picking all commits related with aggroup, ready to merge on upstream. I will start discussion on gitter

That put my work in sync with upstream, waiting to merge (by now that will not happen in near future)

If you can rebase your work on top of aggroup branch you will be ready to merge once aggroup was. I will try latter this weekend.

About workflow. For me branch is just a kind of tag, so after merge I like to remove it. Branch still is there (commit with two parents) so we can revive it at any time if we need to solve anything. e.g:

```
$ git push origin :rfc_t_suite
```

right?

**Comment by amerlyq** [comment]
Ah, alright, glad to hear you like to remove it immediately.
I'm looking forward to your try to rebase master on top of aggroup. Hope it will work out well.

**Comment by albfan** [comment]
Let me know if this is a complete rebase from all your work in top of rking master. 

https://github.com/albfan/ag.vim/tree/rebase-master

I want to start with test cases and differences are minimal to start without this task solved.

**Comment by amerlyq** [comment]
Seems like all there. 
Where you propose me to work now?
Continue to work and merge FB only into master or only into rebase-master?
If last, than what to do with current not-merged featurebranches?

**Comment by albfan** [comment]
I will rebase all branches then. I find
- feature_args_derive 
- feature_mappings 
- feature_operator

right?

**Comment by amerlyq** [comment]
Yes, they are.

Therefore, I understand this as "continue working only on rebase-master",
right?

But then why your master is needed at all, if it will not receive any new
commit/merge? Or you want to merge into both main branches simultaneously?
And then why duplicate work?

**Comment by albfan** [comment]
rebase-master is an example for rebase. Is it correct? Then replace master with rebase-master.

I found there was some merges on master and feature_args_derive so I rebase again with `--preserve-merges`.

Check repo now. All branches are rebased on top of rking/master. As all seems correct rebased tips become new tips.

If we want to keep in sync with rking, we can rebase or merge its changes from time to time. For me, on projects with few people seems better to rebase upon upstream rather than merge. But let's see how it goes to decide.

For me this issue can be closed, as we have all changes ready to merge with upstream. Another thing is if the will be accepted. That can be anoher issue, or a proposal to squash all this stuff, but about workflow, we are in sync

**Comment by amerlyq** [comment]
Initially, when you introduced linear rebase-master with all merges squashed, I thought there was some sacral sense;)
I scanned through fork-viewer on hub, now rebased work looks much better. Thanks.

However, I dislike gitter-badge fork appeared after all our actions.
It consumed our old branch history and looks like eye pain for me.
Maybe, you erase it, re-order commits and add gitter again as very first commit of our rebase tree?
Then in fork viewer its fork will not repeat our tree state.

Ah, yes, I inclined to rebase of master in future also. 
Re-cloning after that isn't great deal for me, especially weighting against seamless melding of our changes on each accepted PR.  (P.S. but maybe you know better way than re-clone to update local repo?)

Alright. This issue can be closed now -- as it exhausted its purposes.

**Comment by albfan** [comment]
Say your remote is origin. You can use:
- git remote update origin
- git remote prune origin

anyway many times I do it all manually
- git fetch --all
- git checkout <branch>
- git reset --hard origin/<branch>

if you have uncommit changes use:
- git stash

or commit and do:
- git rebase <branch>^^ <branch> --onto origin/<branch>

You can expose any specific problem on gitter and I will try my best to give you solutions.

About third party systems like gitter, they love to add that PR commits, Let's grant that to him. I do like fast-forward merges but in a few weeks it will be just an oldest ancestor you will not see anymore.

**Comment by amerlyq** [comment]
I think, at some moment in nearest future we will need to rewrite history on master to regroup/squash commits to prepare it for actual PRs.
(Because actual parts are interwined and has sparse fixes for distant features).
As most of our global changes are sequentially dependent -- it will allow to create FB for PR in very easily way. Current alternative -- to cherry-pick them in the end is ugly in comparison.
