### ISSUE TITLE
Operate on normal an visual mode

### ISSUE THREAD

**Issue by albfan** [albfan/ag.vim#22]
Typing is cool, no typing is even cooler

```
<Leader>ag search word under cursor (anywhere)
<Leader>ag serarch visual selection
<Leader>ra (Repeat last ag search or refine after editing)
```

**Comment by amerlyq** [comment]
Those global mappings are also best to be wrapped in `<Plug>` with guards. See [#21](https://github.com/albfan/ag.vim/issues/21#issuecomment-158650014) for full comment.

**Comment by amerlyq** [comment]
I hope, you understand that your mappings like this

``` VimL
if !exists("g:ag_shortcuts")
  let g:ag_shortcuts=1
endif

if exists("g:ag_shortcuts")
  ...
endif
```

no one will be able to disable?

**Comment by albfan** [comment]
You are now collaborator, so you can fix things like that yourself.

As a rule of thumb, always add first an issue, for long explanation. Add a test if it's possible and If change is big, send a PR or open a related branch.
