### ISSUE TITLE
Smarter args to ag

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#28]
Consider using arguments `-w` with `<cword>` to eliminate partial matchings 
and `-Q` with `visual` -- to treat visual selection as is and not like pattern.

**Comment by albfan** [comment]
Uhmm, interesting. Can you prepare a test on a branch with such features?

**Comment by albfan** [comment]
In some way this is related to #11, causing a lot of confusion to highlight searchs with regexp-like symbols.

For me this is kind of complex searches is now the most important feature to achieve.

**Comment by amerlyq** [comment]
See how I implemented this in https://github.com/albfan/ag.vim/blob/feature_args_derive/autoload/ag/args.vim
Check it as-is if you want. It even has some tests:)
I will split that branch in multiple consequent merges and you can test it out on master in couple of days.

**Comment by albfan** [comment]
See `<Leader>ag` is broken on this branch.

I fixed visual shortcut, by current still is broken.

> visualmode([expr])                                              visualmode()
>                The result is a String, which describes the last Visual mode

You cannot relay on that to know if you are issuing shortcut from visual mode, it returns last visualmode used (That's why on master there's a 0 and 1 hardcoded.

**Comment by albfan** [comment]
shellescape works really nice for searchs with complex signs, but breaks multiword searches:
- `:AgGroup ] = getpos("'<""` (with escape applied, sure) works
- `:AgGroup "let hoge"` don't

**Comment by amerlyq** [comment]
Of course we must use shellescape or quoted only. 
For shortcuts shellescape wins, because it's more steady to content.
But for user input we must introduce additional checks -- likewise if first _and_ last character are quotes and then don't apply shellescape -- becase user knows what he is doing? In any case, we need tests for all those corner cases anyway. Also don't sure if it was right thing for you to delete my `s:escape()`, because escaping `#|%` must be doubled and combined with shellescape, not replaced. They solve completely different problems -- first of vim filename substitution and second of shell substitutions.

About visualescape() -- yes, I know. It was used to unleash and unify api, until I will cover it by tests and will search for workarounds. Maybe I would even returned to your way of 0/1 argument or distinct function name, but under unified interface at that time. That link was supposed to demonstrate how to relate ag options and regex with each other, no more.

Beside that, I still search would it be possible to launch external commands in vim directly with List of arguments without joining them in one string for shell -- like it's done in python subprocess.check_output. Possibly using async neovim jobs or tpope's vim-dispatch. Such solution would eliminate problems with shellescape completely. Because we don't need shell underlining, speaking truly.

**Comment by albfan** [comment]
I like execute as python. Sounds great.

My thoughs are that detecting start and ends quotes would be enough.

I just delete escape to clarify change (in that commit context is unused code) but in final implentation it would be needed.

I like the whole style from args_derive branch, seems easy to extend and maintain, and it enable plugins of plugin develop, extending ag.vim with customizable functions in third-party plugins

**Comment by albfan** [comment]
I'm not sure about avoid parcial match searching for `<cword>` so I made it configurable.

**Comment by amerlyq** [comment]
See `:h cword -> :h star`. There written

```
The word used for the
            search is the first of:
                1. the keyword under the cursor |'iskeyword'|
                2. the first keyword after the cursor, in the
                   current line
                3. the non-blank word under the cursor
                4. the first non-blank word after the cursor,
                   in the current line
            Only whole keywords are searched for, like with the
            command "/\<keyword\>".
```

So, there is no chance, that `<cword>` will expand in something, which will not be found by `-w`, because it only adds word bounds `\b` and no more. I see no sense in that option.

**Comment by albfan** [comment]
e.g: Search for `AgGroup` would report  `AgGroup` and `AgGroupFile`. adding `-w` would report only `AgGroup`

I do like to see both results, but understand others want to see `AgGroupFile` only when search explicity.

I have added a first implementation for `-Q` usage, but would like to add test using isolate sandbox for different test groups. I will reopen #29 to discuss.

**Comment by albfan** [comment]
I have added a failed test on master (expected to fail) and a fix on branch `fix-visual-cword` (basically removing addtion of `-Q` `-w`)

https://github.com/albfan/ag.vim/commit/66e0938e31de9120770f4883fe51a0beb02c3170

Seems ag.vim is not ready to apply automatically `-Q` and `-w`

I'm prone to remove it until different approach to manage args is adopted, where things can be easier to implement

**Comment by amerlyq** [comment]
It's exactly what I called "resolve many other issues much easily" in #80. Long for.

**Comment by albfan** [comment]
Problems here are related with adding quotes on `-Qw` which fulls systemlist(). Better control argument calls is sure the way to go. But by now is more stable without that additions
