### ISSUE TITLE
Refactoring of suite.sh

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#29]
There are manu obsolete/bloated constructions inherited from intermix of sh and old bash.
All code simply refactored, keeping old logic. 
But need thoroughly testing in all previously used usecases.
Merged into master to test on travis in f064aa0bb3385f10f34051882dcb07912fb5b327.

**Comment by albfan** [comment]
Except introduction of `[[` bashism, all rocks. Remember to add #29 to link commits and issues.

**Comment by amerlyq** [comment]
For refactoring I think about issues only post-factum, sorry. Rewrite history to add?
Or only take notice for future?

**Comment by albfan** [comment]
As you will. I love git rebase feature, and put commits in context from issues, but all your commits are plain to understand without link.

**Comment by albfan** [comment]
There is three movements I dislike about test suite:
1. Annoyed flickering on silent mode. Use of `vim -e -s` should be the way to launch suite, without flickering.
2. Remove of numbers on test: Although inmature at this point, some order apart from descriptive name is desired on test. Mature test suites define ranges for config, mappings, functionality, etc. Now has no sense but always can define a logic order in which test should be executed.
3. Move test to `tests/` dir: I do prefer test at first level directory, seems a common standard. At this level would be defined too sandbox fixtures relative to each test. I know you feel this generates repeated fixtures, but to make sense, different test should have different fixtures, there's nothing wrong to use same fixture for different test, but that adds the doubt about changes or refinements detected to a test would break other unrelated test. Rule of thumb: For every test needing a fixture, add its own one.

These guys can't be wrong:

https://github.com/git/git/tree/master/t

On doubt, use conventions, these way probably you will be apart from problems already resolved from other teams, and know environments ease collaboration.

let me know your thoughs, I prefer to be in sync about that before continue extending ag.vim

**Comment by amerlyq** [comment]
1. I also would prefer that way with -es. OK, I will investigate return codes and adapt suite for them.
   Hope `1` for OK is predetermined way for Vader and not some bug, though...
2. Complain. Unit tests must be orderless. If you need specific order -- lauch them manually by 

```
./suite.sh -v cmdline grp qf
```

Now `suite.sh` supports automatic numbering and allows using regexes for names, therefore it will not be great deal to specify them as you wish. Reordering by renaming files only creates unnecessary commits. 
3. Agree. See #49. But on contrary would like to move `suite.sh` and `helper.vim` in root of `ag.vim` or in separate dir `scripts` -- which you prefer more (I vote for `scripts`). I don't like to mix them together, when there will be more than 5 tests. It was main reason to create `tests` dir.

**Comment by albfan** [comment]
Let's forget about numbered testsby now then.

Now helper.vim has absolute paths is fine to move it to scripts, but since it is a helper for test can see why you prefer to move outside t/ dir, but do it and see how it goes.

**Comment by amerlyq** [comment]
A note, or whatever: "These guys can't be wrong:".
Any guys can be wrong. Most of them even realize it sooner or later.
But it doesn't mean they will assault all their old not-so-perfect-but-working code and rewrite it "right way".
Therefore your links could be used as reference, but not as doctrine.

**Comment by amerlyq** [comment]
Using `-es` has drawback of printing some additional text of vim's own operations, which earlier were discarded. It seems, the main reason is using `:grep`. I will try to silent it as for #32 when have time.

**Comment by albfan** [comment]
Looking into this seems vim is not able to suppress output from :grep at this time

https://github.com/vim/vim/issues/529

by now is ok this way.
