### ISSUE TITLE
Define GetArgs/Repeat abilities

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#30]
Referring to `AgGroupLast` renaming [question](https://github.com/albfan/ag.vim/commit/ebf90d10772b62903f41989b39edd028c8ef29a8#commitcomment-14684926) there have arised necessity to reconcile default behaviour for all functions, as them will use `GetArgs`.
- ¿ no arguments -- cword | or repeat-last? == which one _really_ must have separate function?
- selection 'v' one-/multiline -- search as-is `-Q` (agreed).
- ¿ selection 'V' -- is it has sense to search whole lines?
- ¿ selection 'C-v' one-line --  search as regex (w/o `-Q`)?
- ¿ selection 'C-v' multi-line -- feature? -- do consequtive searches | search for any of lines?
- using c[wW]ord for searching?
- ... is there any other cases I missed?

**Comment by amerlyq** [comment]
First question `cword/repeat` groundings -- each command must have both commands, and creating distinct mappings for each one can be too much. Then we can't keep mappings simple and distinct.
To distinguish cases for `cword/repeat` one can use v:counter, how about that?
Simple `<Leader>ag` -- searches `cword`, but `1<Leader>ag` searches previous request.
However, it contradicts your idea of setting `-C` argument (which, nevertheless, usefull only for AgGroup).

Another variant -- we can have **one** and only one repeat -- it will repeat any previous search -- saving full cmd string instead of only arguments. Then it can be mapped to `<Leader>a.`. I like this last idea. Your thoughts? Do we really need distinct `repeat` for each command or united one?

**Comment by amerlyq** [comment]
One of cases -- repeat last search in current visual selection.

**Comment by albfan** [comment]
Concept behind repeat is refine search after edit. Say you are looking for `3.14159` to change into `pi` and there's 30 results. After several editions you want to refresh search to see actual undone work. There must be only one repeat last ag search command.

When decisions are unclear just take the simplest approach. Define commands for all this ag searches you describe and create a customizable <Plug> mapping. Document it and let users find the perfect match. For me `<Leader>ag` works for you `<Leader>a.` seems better. Many plugins offers alternative configurations or mappings, that could be the easy way to find the solution

**Comment by amerlyq** [comment]
Repeat meaning can be extended:
- repeat last search as-is  (for incremental editions)
- apply new regex/flags on last files/locations  (framed exploration)
- apply last regex to new files/flags  (selective exploration)
  (Maybe, decide by checking args count and if first one has quotes? Unreliable...)

I think, maintaing last history (and accessing it through `v:counter` specified to repeat) has not much sence, because there already is `colder/cnewer` for results and command history itself. Or you can think out some usecase for history?

**Comment by albfan** [comment]
All those refinements would be great, as those are basically which I do manually on regular basis.

Just need to be well defined and probed.

Thinking about these situations were UI/UX is the main goal makes me miss a kanban workflow with user histories, task, subtask and milestones.

 https://waffle.io/albfan/ag.vim

Seems all should be labeled and there's no subtasking and way to make relations, but it's just a try. If you now better options let's try it

**Comment by amerlyq** [comment]
Thoughts for history: what to do if pattern is not found? Save it or not as last one for repeat?
- If choose to skip -- we must renew `s:last_*` only after successful search. (if `v:shell_error`)
- For partial repeat -- we must save last command anyway to reuse parts.
- It has some sense only for full repeat. 
- However, is there usecase, when keeping cmdline for last _successful_ search and repeating it becomes useful? (In context of both commands and mappings)
  == Currently, I haven't found even one application. It introduces more obscurity then comfort.

P.S. seems like I also miss some kanban features:)
Issues can describe why and what smth had been done, but not _why wasn't and will never be_.

**Comment by amerlyq** [comment]
Aah, I have remembered, that we have no `colder/cnewer` for `AgGroup`, because it's only scratch buffer. Of course, we could open new buffers as listed when explicitly told, but them will clash with file buffers and cram airline bar. Therefore question for maintaining last search history is reopened, because by using mappings we aren't saving anything in cmdline history. 
Did you had any desire using ag, to repeat more older searches with `AgGroup`?
I had such with `Ag`, but there always was `:colder`.

**Comment by amerlyq** [comment]
I have found in my old code some nice trick: we can use double '!' for commands.
Like that `:Ag!!` or `:AgGroup!! <patt>` -- in those cases first '!' is `<bang` and second -- 1st arg, which can be easily distinguished by space presence between bangs.
Therefore, as simple command -- search, and command with bang -- search and open first, then two bang could be bound to search and open all files. Then you can apply `AgBuffer` to search in these opened buffers. It's only idea, though.
Because incremental filtering demands more than one command implemented to be useful.
Tell your thoughts, for what we could use '!!' beside that?

**Comment by amerlyq** [comment]
I again have analyzed `man ag` and our usecases. Seems like `range` argument for our commands is useless, we have no place to apply resulting `<line1>,<line2>` as interval for anything. And truly speaking, there is no need. One and only case when range is allowed -- it's when applying `:Ag` to visual selection. Therefore we can drop support for all other ranges. Therefore restricting mechanics for `cabbr` to close #51 is greatly simplified.

However we can use 'count' argument, it's useful only for `-[ABC]` options. And until now, as `-C` is used in 90% cases, we can treat this relation as established. Therefore when directly executing commandline, `:3AgGroup` must set `-C` to `3`. For mappings -- we continue to use v:count. If for some choosen commands counter is useful in another meaning, we decide it later. 

Commands' `<bang>` I propose to use for choosing first/second set of filter/ignore/pathes options, as described in #68, #69.

**Comment by albfan** [comment]
AgGroup works this eay already. Except to define bexore and after with range (and feels extrange) can't see use for ranges. Again agreed with change to bang

**Comment by amerlyq** [comment]
We can't use range for before/after because vim will swap them
unconditionally if range end number is lesser than it's start - therefore
-A will be always bigger. Better to drop its support completely and set
-A/B through AgSet\* if someday it will be needed.

**Comment by albfan** [comment]
Perfect
