### ISSUE TITLE
Integration with environment

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#31]
I have been using my simplistic script `ag-vim` to show results of searches from shell directly in vim. If it has sense, it could be improved and bundled with vim plugin. Then symlinked somewhere like `$HOME/.bin` whichever you added to `$PATH`.
- `ag-vim -:<L><[bfhg]>` -- can be aliased in shell to `agv, agb, agf, ..., aglv, aglb, ..., agg`
- open qf/loc/group window in fullscreen on vim start, resize to default on choosing result
- possible additional settings for vim when working in _exploration_ w/o intention to edit.

**Comment by albfan** [comment]
Let's see that script to judge. Remember there's ag_prg

https://github.com/albfan/ag.vim/blob/master/autoload/ag.vim#L6

to change the native shell command

**Comment by amerlyq** [comment]
You can take a look on refined draft of such script at my [bin/prg.d](https://github.com/amerlyq/airy/blob/master/bin/prg.d/ag-vim). It's not complete yet, however, requiring thorough usecases.

**Comment by amerlyq** [comment]
Note: `g:ag.last` can be used to setup 'default' pattern to search by AgRepeat on vim start, evading arguments parsing. Can simplify script feeding.
