### ISSUE TITLE
Fix: make completely silent execution of Ag* commands in vim/nvim.

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#32]
Currently on exec there is once blinking shell before showing output.
Investigate is it possible to suppress such behaviour.

**Comment by amerlyq** [comment]
There is alternative to `silent! exec read!ag ...` by using eval reg: `:put =system('ag ...')`. 
(Also, seems like all `read`-like expressions add after 1st line. Then you need explicitly delete it after command execution by `1delete _`)
Maybe also use direct `:cgetexpr system('ag ...')` instead of overcumbered built-in `grep`?
It will cover this issue and make code more robust and flexible. What you think?
(Edit) Is there really reason to use `grep` -- it's the questions. Original commiter could find some bugs and then read manual deeper than I, resulting in using `grep`. Or he scratched surface and came up with the first one known to him?

**Comment by albfan** [comment]
It use grep because it comes with quicklist bundled. Has sense on one line resuls but useless on context searchs like AgGroup.

I have to confess I never use other commands than AgGroup so I didn't notice any blinking, even on large codebases but let's see what you got.

**Comment by amerlyq** [comment]
Can't understand why last commit to `silence` branch fails on travis, but works on local machine.
Can you take a look, please?

**Comment by albfan** [comment]
See silence-debug branch

Expand logs with pwd, system (ls -R) etc to understand what's happening

**Comment by albfan** [comment]
As you can see messages show that plugin found no matches. There's no error (at least at that point)

Maybe we can add a debug variable to trace execution?

**Comment by amerlyq** [comment]
When I set up travis for my projects year ago, my inability to simply ssh to travis and fix problems interactive really-really frustrated me. Aah, yes, we need to add some kind of tracing under option `--debug` for script. Don't have much time after work this week though -- to think out some nice tracing support for vim.

**Comment by albfan** [comment]
https://github.com/vim/vim/commit/39c29ed5118ab513554d1d51d6a98e65f32784ba

`systemlist()` is only avaliable from vim 7.4. travis offers vim 7.3. Can we upgrade vim version on travis?

**Comment by amerlyq** [comment]
Hmm. Travis launch ci in sandbox, therefore no.
Earlier I thought about test matrix of 4 instances (vim72, vim74, latest
vim, nvim) - all with latest ag only (to reduce load on travis). But vim
build time is too great for this - even if we do it once and then use
cache. It's also due to many newer libraries absent on travis. Therefore no
chance.
And I would like this plugin to work in legacy ubuntu chroot...

As I can see, we must check if systemlist exists (or version+ patch) and
provide wrapper based on system() if not.

**Comment by albfan** [comment]
vim is not that hard to compile 

https://github.com/vim/vim/blob/master/.travis.yml

about 4 minutes for huge features:

https://travis-ci.org/vim/vim

Anyway provide a wrapper (as it is plain to do) is the best approach.

Exactly check is 

```
if has("patch-7.4.248")
```

**Comment by amerlyq** [comment]
Seems like one of problems, we must resolve in context of tracing, is how to show/hide  output of commands prefixed with `silent!`. Then specifying `--debug` option to `suite.sh` could reveal some errors in the very start of execution without deep tracing.

**Comment by amerlyq** [comment]
Alright, I have installed Ubuntu 12 in chroot on Arch and made some fixes there.
Don't know exact problem, but seems fixed finally.
Thanks for assistance.
