### ISSUE TITLE
UI: Unite integration

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#34]
Think of a possibility to combine `Unite` interface with `AgGroup` and their potential.

**Comment by albfan** [comment]
I do use it a lot to check mappings, and I like it a lot. I tried to create sources several times unsuccesfully.

Yesterday I finished an expansion of local inspections on https://github.com/albfan/vim-breakpts and I use it mostly to inspect complex vimL plugins, maybe is time for another try.
