### ISSUE TITLE
Move ag executable existence check

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#35]
It can be placed:
1. In root function, called on any `Ag*` cmd execution.
   - \+ don't disturb user until he will actually call command, don't affect startup time (autoload).
   - \- once installed binaries very rarely can (dis)appear between ag calls, excess checks.
2. In the beginning of `autoload/ag.vim`
   - \+ also don't effect startup time
   - \- echoed message can be ignored/unnoticed
   - \- defined commands will be broken
3. In the `plugin/ag.vim`
   - \+ most clear way
   - \- affects startup time (but can be lazy loaded by package manager)

Do you have your own proc/cons for some specific usecase? 
If not, I will change according to 3.

**Comment by albfan** [comment]
I'm byased to first approach (don't disturb until used) but third is reasonable for this plugin as it is tighly related with ag.

**Comment by amerlyq** [comment]
Ok, approach 1 was implemented in 6ce5be6fe0df8c639a1647820e8e7fcf0653b3a5
However, I think we could implement approach 3 efficiently by defining binding function inside of `if...else` branches. Then one body will be defined when `ag` is available and another with `echom` when not. Therefore I will keep this issue open, until checking code will be moved into `autoload/ag/bind.vim` or back into `autoload/ag.vim` -- but only after all current mess in it will be ordered and distributed.

**Comment by amerlyq** [comment]
Now this can be finally implemented:)
