### ISSUE TITLE
Move options definition in appropriate place

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#38]
Defining them in `autoload/ag.vim` don't work anymore, after splitting into `autoload/ag/*.vim`.
- Like idea to create separate file `autoload/opts.vim` and then rename all options as `g:ag#opts#<name>`. But then all names will became obsolete.
- Temporarily moved into `plugin/ag.vim` -- longer startup, but more compatible with old configurations.
  If then it will be agreed, we return to first case and add `echom deprecated` guards to old options.

**Comment by albfan** [comment]
I was recently working on a well designed plugin

https://github.com/mhinz/vim-signify

It follows the convention of split functionality on dirs and files.

You can use it as guide to divide features on ag.vim. It is a pleasure to work on such designed plugins, will stick on it if you start the change

**Comment by amerlyq** [comment]
It's exactly what I did in `feature_args_derive` branch.
However currently I didn't break back-compatibility with old options.
When it would be done, them will look as in `vim-signify` -- as unified global dict with all options.

``` VimL
" Unified options dict declaration in 'autoload/ag/opts.vim'
let g:ag = extend(get(g:, 'ag', {}), { 
\ 'key': value, ... 
\ }, 'keep'}
...
" Usage
if g:ag.key == ...
```

I have done same way in https://github.com/amerlyq/vim-focus-autocmd

**Comment by albfan** [comment]
So we're aligned about coding style. That's a big step.

**Comment by amerlyq** [comment]
When you want to break backward-compatibility in options by introducing above mentioned dict?
We can tow it all way out until the very end, using anywhere old-style options.
Or we can break them as soon as possible, and base all future changes on great looking new-style.
I have prototypes, but there no sense in keeping them in separate branch, because it's overhaul by design. And I need this decision to adapt splitting of feature_args_derive.

**Comment by amerlyq** [comment]
Alright, lets break backward compatibility.
I think, we already decided that options will be contained inside dict.
There are two appropriate places for them:
- `autoload/ag/opts.vim`
  - \+ load on demand, postponed checking of `ag --version` 
  - ~ but it's only minuscule advantage in 0.2...2 mS of startup time, profiled on i3/HDD
  - \+ whole file only for options, nice splitting of code
  - \- ugly dict prefix everywhere `g:ag#opts#opts.<key>`
- `plugin/ag.vim`
  - \+ initialized as earlier as possible
  - \+ nice dict prefix `g:ag.<key>`
  - \+ all user-interest commands/mappings/options placed in one place -- it's great for beginners
  - ~ slightly overcumbered `plugin/ag.vim` with options + commands + mappings
  - \- longer startup time -- but it's not that great problem due to above profiling, and we always can lazy-load with plugin managers
- Combined -- placed into init func in `autoload/ag/opts.vim` and called from `plugin/ag.vim`
  - \+ all the code-isolation from 1st approach
  - \+ all the simplicity from 2nd approach
  - \- no lazy; maybe slightly less clearer, but controversal also possible

**Comment by albfan** [comment]
I do prefer config options on the file managing related functionality

Continuing with vim-signify example: see `g:signify_sign_show_count`

```
$ ag -u signify_sign_show_count
```

But do the way you prefer, or better the way more easy to maintain.

**Comment by amerlyq** [comment]
I understand your point. This approach has advantage in coupling options with related code -- which is nice for developing, but only until options quantity is small. Also it has advantage for performance -- loading options only when they are really needed, but minuscule, truly speaking. 
And all of this by the cost of readability and manageability.

Help becomes single place where you can see what is controllable and what is not -- it's disadvantage, because for many plugins it's really-really easier to read their definitions than help. You can't do anything with options as whole. All your tweaks (like ag version decisions) will be scattered and their order becomes unmanageable. 
In ~15 languages, which I used to write something more than several hundred lines, distribution always was supplanted by isolation -- by architecture alone, not by whim. 
Because options are subsystem state after all, and they are subsystem by itself.
