### ISSUE TITLE
slow down on test suite

### ISSUE THREAD

**Issue by albfan** [albfan/ag.vim#41]
Using --verbose mode is faster than normal (silent) mode.

All is related with vim warning about ouput is not a terminal

> Vim: Warning: Output is not to a terminal

Some folks resolve it using ex mode silent

https://en.wikibooks.org/wiki/Learning_the_vi_Editor/Vim/Modes#Ex-mode

but in my tries, ex-mode exit status is 1 when all is ok and 2 when test fails.

**Comment by amerlyq** [comment]
After more investigation I found we can't suppress this issue by shell means.
So using `-e/-E` is obligatory. But exit statuses, heh...
Seems like it's bug/feature provided by `Vider`. Checking last commands which returns error status in its sources and contacting author -- all our choices at the moment.
Or we can change screapt to treat another codes as OK and FAIL.
By default  command, crafted according to vim help, works as expected with 0 exit code.

``` bash
# Manual test: try using pwde (mistyped) instead of pwd (correct) to receive error code
  vim -i NONE -u NONE -U NONE -nNEsS <(echo pwd) -c'echo""|qall!' -- <(<~/.bashrc)
# But when used in suite.sh -- returns non-zero because of -c'Vader!' -- try to remove it and re-run
  vim -i NONE -u NONE -U NONE -nNesS ../helper.vim \
    -c'Vader!' -c'echo""|qall!' -- ../${file} >/dev/null 2>&1
```

It would be nice if you notified @junegunn to take part in this issue discussion.
(Edit) Take into account that appending to `../helper.vim` some commands with guaranteed zero exit code makes no difference. It's completely `-c'Vader!'` fault.

**Comment by amerlyq** [comment]
By the way, using `VIM=nvim` in `suite.sh` don't produce any verbose information at all.
Not big problem, but anyway...
(Edit) I re-checked this, with nvim it produces trash of control-codes, which clears all outputed information when interpreted by term.

**Comment by amerlyq** [comment]
@albfan, I can't understand if we use `vader` incorrectly or what.
Having several `*.vader` files, we launch `vim ...` on each one separately, therefore output info is messed with repeating calls to `vim --version`. It's irritating trash which he [wontfix](https://github.com/junegunn/vader.vim/pull/60).
Maybe we supposed to call all `*.vader` at once? Like `Vader! *`?
Or there is objective reason to call each file separately -- like at that link?
I will add filtering output with sed -- and call `vim --version` only in `.travis.yml` -- because anybody knows/can_check his vim version anytime.

**Comment by amerlyq** [comment]
Seems like workaround for this is to only use redirection for stderr and don't touch stdout at all.
But it's only partial solution working with launching `suite.sh` in terminal, as any consequent redirection will resurrect problem with vim delay.
Anyway, I will merge this fix.

**Comment by amerlyq** [comment]
Reopen issue only if you want to handle troubles with `Vader`.

**Comment by albfan** [comment]
We launch test separately to allow suite to control failed test and title, but surely we can launch it with `Vader! *.vader`

The problem redirecting only stderr is a blinking on every test. Avoid that slow down maybe deserve that noise.

Are you sure Vader is the blame on exit status 1 and 2?. Former version of suite do use `Vader!` and exit status are 0 and 1. Please provide details to open an issue on Vader

**Comment by amerlyq** [comment]
You can simply try with/without that -c Vader! term, as I commented in last
to previous post with cmdlines. Check it out in terminal, it's narrowest
bounds I have now. Any more details require its sources investigation. And
I hope finally to concentrate on tests now -- main goal of all this noise.
So if you can...
