### ISSUE TITLE
Test results delusiveness

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#42]
In testing suite we use options to enable default vim behaviour and disable any influence from divergent user configs. It's great for reproducibility of tests results, but bad overall -- because we lose integration errors, caused by user environment with many interfering plugins.
Of course I will add one more option to `suite.sh` to run tests in user env on demand.

But it reveals deeper problem -- all such tests became manual labour of independent individuals instead of automated checking on CI server.

**Comment by albfan** [comment]
We can always add an it/ dir to do integration test. I would drive it from reported errors or conflicts, but that is just my point of view.

Let me known any existing problem to start to resolve it
