### ISSUE TITLE
Add fallback sequence (ack, grep, etc)

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#43]
Working in embedded with legacy code I'm often attached to chroot with old kernel and only minimal set of packages. Switching in/out chroot dozens times a day, I setted up somewhat compatible environment to not interrupt workflow. But `ag`, of course, is absent.

It wasn't big problem earlier, as `ag.vim` only provided simple wrapper plus several features, most of which I disabled anyways. But now I would like to treat plugin as general search interface, which can work as is. Though such feature somewhat more wide than original plugin name, but splitting UI and core isn't such a bad idea? 

After all we anyway make separate command composition, launching, results processing and interaction with them. 
(P.S. Launching must be separate to introduce neovim jobs or vim-dispatch tasks).

**Comment by amerlyq** [comment]
Therefore, this task consists of:
- [ ] generalize cmdline compositor to be independent from search provider
- [ ] isolate search provider launching.
- [ ] to unify format of search results,  add post-filter if necessary
- [ ] add fallback sequence of configured search providers

(Edit) Source of inspiration and necessity:
https://github.com/Shougo/shougo-s-github/blob/master/vim/rc/plugins/unite.rc.vim#L178

**Comment by albfan** [comment]
Like the idea. But feel like we should start another repo for that. Surprisingly "vim-search" is avaliable (there is a https://github.com/xudafeng/vim-search, but seems pet and stagnated)

If you prefer to refactor this plugin, let's start a branch and a test about fallback sequence for basic searchs. Once that is completed, the rest is just hack.
