### ISSUE TITLE
Propose to add hooks

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#44]
As we rewrite history more-less frequently, I propose to add git hook at least onto push in master.
I think it can be helpful, to run tests on your own machine before actually pushing into master (other branches we allow to be broken).
See one of links how to do it:
http://blog.ittybittyapps.com/blog/2013/09/03/git-pre-push/

**Comment by albfan** [comment]
Uhmm! good, but little late check in my opinion. 

I use tmux with a split vertical. On one side vim, on the other a inotify script runner 

https://exyr.org/2011/inotify-run/

add that script to your path and issue:

```
$ inotifyrun t/suite.sh -v -c
```

On every change you write, testsuite will be launched (instant feedback). Try it with a simple 

```
$ touch autoload/ag.vim
```

Tip: normally you use all screen for vim (prefix z or tmux resize-pane -Z) and check test pane from time to time. or you can use a notification:

```
$ inotifyrun t/suite.sh -v -c || notify-send -u critical -t 5000 "ag.vim testsuite broken"
```

Both approachs can be added to a developer page wiki on ag.vim

**Comment by amerlyq** [comment]
Nah, simply for launching tests I have my own approaches. 
And I'm saving too much often to use inotify for this. Shortcuts are easier for me in my workflow.

Main goal for that push hook -- is not in launching tests at least once before pushing in master, reducing your own manual labour. No, it's main goal is to control numerous history rewritings. We could, of course, specify recursive inotify on whole dir of ag.vim, but it will be such pain when tests number increase and their runtime became much longer... When this will become the case, you will disable your recursive inotify until history rewriting done. And thereafter there will exist possibility, that you won't check tests the very last time before push. Therefore, git hook on push.

**Comment by albfan** [comment]
You're right. Can you start a wiki with your hook? Would be really helpful
