### ISSUE TITLE
Use /tmp for temporary files of testsuite

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#45]
I don't know which goal you carried when chose to clone `vader.vim` and create temp.XXX in `ag.vim/t`. If you have reasons, clarify them please.
For me /tmp is placed completely in RAM, is predefined place for such tasks, etc, etc...
As I switch between branches frequently it's much better option to clone there, instead of current directory.
I will provide appropriate changes to `suite.sh`. Portable for Windows too.

**Comment by albfan** [comment]
It comes from replication of https://github.com/mlafeldt/sharness behaviour (a testsuite derived from git). I guess it is based on don't assume you have rights to write in other directories than actual.

You can see in use here 

https://github.com/albfan/git-ignore/tree/master/t

I see a mistake of mine about add vader.vim to history. That's wrong, I will remove from master if it is still there.

Untracked files shouldn't have to be a problem when switching between branches.

But if you want to change to tmp/, do it and we will see go it goes.

What is needed to change is to create fixtures for different test.

```
- 01-aggroup.vader needs a 01-aggroup dir
```

That way we do not pollute fixture files with different scenarios irrelevant from test to test.

**Comment by amerlyq** [comment]
Alright, I have completed work on `tests` branch. 
Will merge it after mentioned by you reorganisation of tests/fixtures or something along that.

By the way, if we use separate fixture for each test, what you think to do with identical fixtures then? 
- Duplicate? We shouldn't use relative symlinks inside git (clean and nice solution as for me), because this will not work under Windows. 
- Make matrix of test--fixture? Too rigid, and we lose attaching tests by wildcard like `*.vader`.
- Add another header to tests -- like you did with commet `""" Check AgGroup command` -- most clean way from these three. Best?
- ... smth better?

Overall, I think fixtures are related to groups of tests, not to individual tests itself.
Therefore that 3rd approach wins, because better only parametrized tests, absent in vader.

**Comment by amerlyq** [comment]
And yes, vader.vim is still there somewhere hidden.
When I removed guard from gitignore and deleted vader, it showed itself.
Clean, please.

**Comment by albfan** [comment]
Error was introduced on f55ef75b2db70e527202f021d6526620798984d2. check for version was fixed on rking master and I added wrongly t/vader.vim. Now that there's only two branches can be easily removed, but as you comment your problems updating your local clone after rebase, by now I simply add a commit on master and cherry-pick on feature_args_derive.

If you prefer rebase this time let me know. Any problem updating you clone can be resolved easily (using gitter or tmux remote or similar)

**Comment by amerlyq** [comment]
Forget about my problems with git clone, please. I can't reproduce those problems in repeatable way, therefore dual session give me not much more problem solving. I need more background on git internals for this -- will take my time someday.

About feature_args_derive -- I will disintegrate and abolish it in couple of days, therefore no need in cherry-pick. Please, do rebase and remove vader from history completely. It will simplify merge with upstream then.
