### ISSUE TITLE
Fix: escaping repairing and unifying for cmdline

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#46]
Unifies discussion at #27 and #28.
I have created fail-test. Need more.
Next I will commit appropriate piece of feature_args_derive.
Will be kept open for all not fixed aspects, described in natural order.

**Comment by albfan** [comment]
I know you know it, but when you define something you know is failing (defining a bug or a pendent enhacement) mark it as failed

```
""""failed
```

We can extend keywords for known failed test as `""""bug`, `""""enhancement` if you prefer. For me failed is enough.

**Comment by amerlyq** [comment]
Reopen this if any problem persist or new ones arrive.
