### ISSUE TITLE
Fix: right buftype for each type of search results viewing

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#47]
Currently all code in ag.vim is intermingled and partially duplicated.
I don't want similar thing in tests.
Each `Ag*` command must provide it's own view interface, but not whole core, as it is now.
`LAg` is wrapper for `Ag`, therefore there is no necessity in separate tests.
But we must check opening right interface on search and focusing on its window:
- The same viewer, only one window.
- Different viewers one-by-one, but only one window opened at the same time.
- Different viewers, multiple windows at once -- like after `Ag` and `AgGroup`.
  Need to enhance current testcase and fix window opening problems.

Current problem of buftype -- `getqflist()` isn't empty after window closing.

**Comment by albfan** [comment]
Can see problem underneath. e.g. When you issue AgGroup, could be a prior :grep command (launched or not by ag.vim) and AgGroup shouldn't clear that, even more when it is on a different result buffer.

Why a command should clear other results for its execution?

**Comment by amerlyq** [comment]
It must not, of course. 
But there not that many ways to distinguish `qf` and `loc` buffers.
It's currently googled way; skeleton if you wish. 
Tests must be fixed with valid and distinct checks. Any other working way will do.

**Comment by albfan** [comment]
I think lot of deduplicating is done on feature_args_derive. Maybe there is clear to see purpose for this test. I mean, we need to check that in order to... what?

What feature we cannot add or achieve meanwhile that skeleton test (or a definitive version) don't pass?

**Comment by amerlyq** [comment]
Hm, your own words -- about lazy, etc, etc.
Tests first, fixes later. Currently which window you open on which shortcut _seems_ obvious.
But then, after you starting to unify interfaces, it becomes much more obscure.
Especially when there more than two windows opened. We must check that all windows are there, no one was closed unintentionally after our last search, etc, etc.
Therefore this test -- to be sure opening/closing interface works as expected. Treat it as QA for future.

**Comment by albfan** [comment]
Ok. Normally test cases are self explanatory, consider using `""""skip` and comments with task to be check when test case is at this level of definition.
