### ISSUE TITLE
Propose: fixture as list of corner-cases w/o specified syntax

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#49]
Maybe you fondly attached to `*.vim` so you used that format for fixtures, but it's overcumbered for testing purposes, introducing unnecessary complexity in `Expect (...)` block and hampering overall covering.

I propose to change format of each fixture to next:
- Plain list with only corner-cases, each one on separate line -- then each "Expect" becomes clear 
- No additional text before/after actual corner-case, beside where it matters -- we already assumed ag itself works correct!
- Text content is derived from actual corner-case -- it will clarify their purpose. Examples:
  - "quotedword"
  - raw multi word
  - escaped\ multi\ word
  - 'squoted multi word'
  - (re[ge]x|)
- Text inside parenthesis of `Execute (...) / Do (...)` blocks must repeat text content above -- then we will be able to see what was tested in log of non-failed tests -- which is great. No necessity to specify long sentences as you did -- smart splitting all tests in files will do this work better than you could.
- All searches on that fixture must return only one result -- K.I.S.S
- Multiple results in one search -- it's separate corner-case with its own testfile.
- Same for testing right highlighting -- separate dir + testfile only for this purpose.

Now about structural organization for all this (Edit):
- One individual fixture for each *.vader (as you proposed) -- one dir with identical name directly in same dir, like `ag.vim/t/<test-name>`
- Script `suits.sh` will copy appropriate fixtures into temporary dir of launched tests as before.
- Move `suites.sh` and `helper.vim` into `ag.vim/scripts` (prefered) or `ag.vim` (root) to decouple heterogeneous stuff. (That dir can be used for other scripts in future)
- Create makefile with target `make tests` -- possible only after introducing -es

Complaints, please

**Comment by albfan** [comment]
Agree almost to all. I'm glad you detect test description are little confusing actually. I found myself opening test to see its internals which clearly shows it has bad descriptions.

fixture extension is only for handy highlight, without using modelines. I found plain files noisy and confusing.

This guideline can be part of another wiki page, but don't be too rigorous about tests, different scenarios would need to contravene some of these rules, although at first sight all sounds correct (I'm thinking on testing mappings to jump between results in AgGroup which cycles forever on results, needing more than one search result)

thinking on #42. Do you want to propose some integration test for potencial problems with environment? that should be an informative testsuite, which didn't break build, but automatically inform for problems with desired co worker plugins.

Another thing I would like to add (but is just a user history on vim-breakpts) is to add code coverage to script https://github.com/albfan/vim-breakpts/issues/28, to see what is not checked yet by test suite.

**Comment by amerlyq** [comment]
Of course rules not strict:) Only main guideline -- to do it wherever possible, not where impossible.

I also don't like plain files and do like syntax highlighting, but in this situation using concrete syntax will force you to add unnecessary decoration stuff to gratify complaining `syntastic` and broken syntax highlighting for uncomplete expressions. Besides, I don't know how much useful for you highlighting will become, when all fixtures will be looking like column of one-two words with optional symbols inside/outside.

No. Currently I have no intention to deal with integration testsuit, feel free to do whatever you think appropriate. I would liked to order my own stuff at least...

I'm appreciating idea of code coverage. Waiting impatiently for this;)

**Comment by amerlyq** [comment]
I haven't touched tests for AgGroup and its fixtures. Please, do something when you in mood.

**Comment by albfan** [comment]
Ok. I would check it and rework.
