### ISSUE TITLE
Enh: use cabbrev instead of Agg command

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#51]
You introduced renamed command Agg and deprecated AgGroup to be able type it easier.
It's as always good idea, bad suggestion.
Explicit command name is more clear than obscured one -- see bad practice of NrrwRgn.
If you want to resolve it, vim community already developed another practice: cabbrev.

``` VimL
cabbrev Agg AgGroup
" Or even simpler
cabbrev agg AgGroup
cabbrev aggf AgGroupFile
```

Then if you type it and press enter all will work as expected.
If you type it and press `<Space>` -- command will be expanded and clarified.

**Comment by amerlyq** [comment]
And, by the way, all those abbreviations also could be guarder by `if g:ag.use_abbreviations`, like mappings.

**Comment by albfan** [comment]
That was my first choice. I tried several ways and didn't work (using cnoreabbrev). Don't know exact problem. Have to check again, I would prefer to use cabbrev

**Comment by amerlyq** [comment]
Maybe it's problem with your vimrc? Because it works for me.
Even with `cnoreabbrev agg AgGroup`.

**Comment by amerlyq** [comment]
Check out please workability of `abbrev` branch for you.
Lets find the root of your problems with them and if those problems will be persistent for another users.

**Comment by albfan** [comment]
Don't know what happen, but now works as expected. Anyway I dislike abbreviations for commands. I think abbrev is a nice trick to enable lowercase commands, but when agg expands to AgGroup is a bit annoying.

Anyway... All is ok with branch `abbrev` merge it to master.

**Comment by albfan** [comment]
I have done it already

**Comment by amerlyq** [comment]
Hm, seems like cabbrev is not that smart. And your short commands don't seem that bad after all.
We need `<expr>` mappings, to expand them at cmdline beginning _only_ and not in any other place. Like this: http://vim.wikia.com/wiki/Replace_a_builtin_command_using_cabbrev
Also see 'Scripts' section there for ready solutions.
More tricks inside 'See Also' of: http://vim.wikia.com/wiki/Using_abbreviations
Therefore I reopen this.

**Comment by albfan** [comment]
Great we both see cabbrev is not a complete solution. Anyway keeping actual implementation on master allow us to check it throughly and see how it goes

I never expect to been comfortable with `jj` as `<Esc>` and not I can live without it.

**Comment by amerlyq** [comment]
Is cabbrev somehow interfere with jj?

**Comment by albfan** [comment]
no sorry, I just mean you need to try something to really now if it works

https://github.com/albfan/dotfiles/blob/master/vimrc#L274

Maybe using actual implementation for alias with cabbrew we realize it is not so bad.

**Comment by albfan** [comment]
As said, after several days using it, cabbrev usage should be fixed. It difficults own develop for ag.vim as using:

```
:ag ag#bind
```

changes to:

```
:Ag Ag#bind
```

http://vim.wikia.com/wiki/Replace_a_builtin_command_using_cabbrev is the easy fix for that. I'm agree to define alias with function pointed on that post:

<pre>
function! CommandCabbr(abbreviation, expansion)
  execute 'cabbr ' . a:abbreviation . ' <c-r>=getcmdpos() == 1 && getcmdtype() == ":" ? "' . a:expansion . '" : "' . a:abbreviation . '"<CR>'
endfunction
command! -nargs=+ CommandCabbr call CommandCabbr(<f-args>)
" Use it on itself to define a simpler abbreviation for itself.
CommandCabbr ccab CommandCabbr
</pre>

**Comment by albfan** [comment]
I have opened a branch `abbrev` to discuss further improvements, but for me this can be closed with this last change.

**Comment by amerlyq** [comment]
Too naive implementation -- it will be again broken in another circumstances, which you haven't crossed out yet. Exactly by that reason I have attached several links and pointers instead of fast copy-past, because this question needed analysis. Also dynamic commands must be mapped with `<expr>` to not mess up cmdline if there will be exception in process.

So, sorry, I rewrote that. See `abbrev-v2`. 
If you agrees with my changes, merge it and remove `abbrev`.

Currenly I see no sense in creation of separate `ag/abbrev.vim` because:
- abbreviations will never have alternative functions like `ag/paths.vim`
- necessary code is too small, disk io on HDD may be more costly then CPU tacts
- moving in separate file has sense only for completely separate parts -- with default definitions
- abbrevs depends on names of commands API -- which aren't stable yet.
- I would like to do those API renaming in bounds of one file
- maybe after API reworking, all that default tables will be merged into one -- and there will be no need to use separate file at all.

**Comment by amerlyq** [comment]
I also like to mention, that current abbrev expansion don't work nor after visual selection `v3j:ag`, nor after current range specification `3:ag` which produces `:.,.+2ag` nor after counter `:3ag`. So there is some room for improvement, rather complex however, to filter allowed cmd prefix on cmdline, like it was done in http://www.vim.org/scripts/script.php?script_id=746

**Comment by albfan** [comment]
Then we have our test cases defined in pseudo code. Now it's only needed to define those cases and submit  changes to support all that stuff. For me my implementation supports all my neccesities, but is great to see more advanced requirements. I guess now we have enough info to fix this issue. Let's work on it
