### ISSUE TITLE
Task: move resources in orphaned branch

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#54]
Relocation of `res/` will allow vim plugin managers to clone only master branch and evade downloading other large binaries. Also it will allow us to add more screencasts w/o affecting user experience.

If you would wish even more evasion -- like not cloning that orphaned branch at all when doing development -- it could be moved into tags like in http://stackoverflow.com/questions/540535/managing-large-binary-files-with-git/31390846#31390846.

I did that earlier in https://github.com/amerlyq/yarxi.pl. 
You can try out final result of such hierarchy firsthand.

**Comment by amerlyq** [comment]
There too much text with theory, therefore compressed algorithm is next:

``` bash
# Adding the Binary Files
    # Create temporary branch with disconnected root, at the end -- delete it.
    # But push on server custom tag instead (so fetch won't dld it w/o --tags)
    gco --orphan tmp
    git rm -r --cached * .gitignore  # keep .git only
    rm -rf *   # keep .git only
    cp -r /path/to/res/ .
    gca "Added res dir, $(date)"
    git tag res
    git push origin res
    gco master
    git branch -D tmp

# Checking out the Binary File (if necessary)
    git fetch origin res
    gco res -- res && git reset
    echo 'res/' >> .gitignore
```

**Comment by albfan** [comment]
github pages and wiki work this way, so maybe is not necessary to do that step manually. That way we get a friendly page for newcommers.

Remember to refer screencast from README.md anyway

**Comment by amerlyq** [comment]
The only common point between introduced resource management and pages/wiki -- it's using orphaned branch. Pages are mostly textual and keep whole history, when for binary screencasts there no much sense in that. Moreover, it's contradictory. Therefore, even if you add branch with pages, you will need separate branch for binary resources nevertheless. Simply by means of efficiency -- to be able to update them separately and don't bloat the history -- as you can simply squash or update the same commit. Rebase will not be much help here.

And note on pages -- I have no intention to manage them, so if you would like to afford this task...

**Comment by amerlyq** [comment]
By the way, I have found notions on web that not all branches are downloaded on git clone by default (you need do it explicitly in cycle -- smth like that) -- and at the same time I never observed such behaviour -- all known to me repos are cloned completely.
I don't talk about `--single-branch`, if you think so:)
Therefore it picked my interest -- can we mark some branches on github as _don't clone me_ or at least set only main development branch (currently master) to clone implicitly (by default `git clone`)?

**Comment by albfan** [comment]
I don't think so. shallow clones are user decisions not server configuration.

About using github pages I mean that  a screencast is better to be stored on a website for ag.vim instead on its develop repo. 

Steps:
- Using templates provided by github create page
- clone
- add screencast and link properly on page
- remove from develop repo
- link README.md from develop repo to screencast to github pages

I'm not planning to create a github page neither, but to remove screencast that would be a solution.
