### ISSUE TITLE
Propose: disallow using raw ag options in cmdline

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#55]
To improve api and remove bunch of crutches, we need separately parse/specify ag flags and pattern.
This will allow to construct ag cmdline more precisely and replace desired parts on AgRepeat.
Current vim can't satisfy this requrement nor with f-args, nor with q-args.
To be able to divide them manually we must re-implement `getopts` func in vimscript and provide full spec for all ag options. Most of which will not be used from vim cmdline anyways.
All of this is unnecessary complexity leading to confusing cmdline arguments.

By repudiation from raw ag flags, we can use positional cmdline arguments and recreate only meaningful flags by distinct binded functions.

**Comment by albfan** [comment]
I guess you're taking about https://github.com/albfan/ag.vim/blob/master/autoload/ag/bind.vim#L41

It is an inherited implementation from upstream, but clearly a weak and bad design.

tagbar https://github.com/majutsushi/tagbar  is a vim plugin heavily based on a native command (ctags) and is rough and consistent. It uses "vim pseudo objects" dict.

https://github.com/majutsushi/tagbar/blob/master/autoload/tagbar.vim#L123

Is a good view of the pain a wrapper against a native command involve, but for a mayor objetive to use ag.vim with a fallback sequence of searchers, maybe is a correct decision.

In some way g:ag.last is a naive first implementation for searcher vim dict wrapper.

**Comment by albfan** [comment]
This is a firt implementation of dict objects. See it allows to control logic used on ag.vim (as adding `-Qw` on `<cword>` searches)

I have marked all test broken as failed. But I guess is easy to fix, and the right way to manage input and final commands for plugin
