### ISSUE TITLE
Avoid reopen buffer edited

### ISSUE THREAD

**Issue by albfan** [albfan/ag.vim#57]
When AgGroup navigates to matches, close and reopen buffer. When buffer is edited, prompt to discard arises.

Detect buffer on target window is buffer for selected match allow to navigate without risk to loose changes.

**Comment by amerlyq** [comment]
You specified some nasty behaviour here. Why jumping needs to close/reopen buffer at all?
How intricate you did all that jump mechanics, if `set hidden` in vimrc must resolve all that by itself but can't?

**Comment by albfan** [comment]
using hidden should work, but the problem is what window to reuse. I think I could solve this easily, but sure hidden will be involved. Let me check it

**Comment by amerlyq** [comment]
I have realized some problem, or think so. AgGroup is in separate window and we must choose window where to show up our search results, as them mustn't show in AgGroup. Maybe we could inherit behaviour of `qf-lists`? Track what it does when there three/more windows and several tabs and how search results will be showed -- jumped to appropriate window if it exsists (what if it in another tab), open new window, or which window will be reused to open related to matches buffer.

**Comment by albfan** [comment]
Sure there's existing implementations that should work.

What is `qf-lists`, a plugin?

**Comment by amerlyq** [comment]
No;) simply abbreviated naming from help

**Comment by albfan** [comment]
This solves major problem, but there's two unresolved:
- Navigate to searchs on edited and unsaved buffers (is needed to find lines added deleted to fix line position or match deletion
- navigate to window with filename open when that is not the aggroup choose. Maybe configurable as it can be on other tab.

**Comment by albfan** [comment]
Only thing left to do is detect modified buffers to navigate to exact line.

**Comment by albfan** [comment]
Since all plugin relays on ag to search, unsaved buffers suffers from this problem on any ag.vim command (not only AgGroup) so I will open this as a new issue.
