### ISSUE TITLE
Disable autoopening first result

### ISSUE THREAD

**Issue by benoittgt** [albfan/ag.vim#58]
Hello

I've check the doc without finding the answer. Is it possible to disable auto-opening of the first result ?

Cheers

**Comment by amerlyq** [comment]
Help isn't in sync, until API refactoring will be completed. So don't depend on it temporary:)

However I don't understand your problem -- `Ag` either `AgGroup` search w/o opening first result by default. `Ag!` -- with. I thought there no great changes with upstream in that aspect?

**Comment by benoittgt** [comment]
As you can see when I run a search it automatically open the first result.

![my_pb](https://fat.gfycat.com/HeftyObedientIchthyostega.gif)

I have nothing specific in [my dotfiles](https://github.com/benoittgt/dotfiles_osx/blob/master/.vimrc)

**Comment by amerlyq** [comment]
I claim there is no such behaviour. But alright. Try to reproduce this problem with [this minimal vimrc](https://gist.github.com/amerlyq/83183bc2b5215f284d80) by `vim -u vimrc_ag.vim`. 
If you still have issue, attach new animation actual for that vimrc please.
If issue is gone -- your problem in your vimrc.

**Comment by amerlyq** [comment]
Of couse, you can adapt my template by replacing NeoBundle by Plug, etc, etc and attach gist with your minimal vimrc, where issue can be reproduced.

**Comment by benoittgt** [comment]
Using this vimrc -> https://gist.github.com/benoittgt/39f2ebd29ba8b3d3c398

`vim -u .vimrc_ag`

![vim_ag](https://zippy.gfycat.com/ClosedSilverElephant.gif)

**Comment by benoittgt** [comment]
Using ~ vim version 7.4.903, ag 0.31.0 and up-to-date ag.vim

**Comment by amerlyq** [comment]
Please, at least check your own `vimrc_ag` before posting it. It's broken. Completely.
Even if I close my eyes on unexisting `gmarik/Vundle.vim`...
If _that_ works on your system, than your dotfiles are broken. Because `vimrc_ag` not independent.
And I ask you _again_ to check with _my_ minimal vimrc _at least once_, before posting yours.

**Comment by benoittgt** [comment]
Thanks for your patience @amerlyq. You were right. With your vimrc I don't have any more the auto-opening. I'm not at work anymore so can't try on my working station but at home with my vimrc cleaned it doesn't happen anymore.

**Comment by albfan** [comment]
I'm sure ag.vim clone is the faulty one. That line 

```
[Quickfix List] :ag --column test app/
```

is not uptodate

should be 

```
Location  :cgetexpr s:sh(a:shellcmd)
```

check if :PluginInstall shows an error updating ag.vim. If you use rking/master you cannot update directly. Remove ag.vim and install again.

```
$ rm ~/.vim/bundle/ag.vim
```

**Comment by benoittgt** [comment]
Thanks @albfan you were right. I've removed `vundle` folder and also `plugged` folder, reinstall with VimPlug and I don't have the unwanted behaviour.

Thanks for your help both of you.

**Comment by albfan** [comment]
You can always change a plugin yourself with `git remote` `git fetch` and `git reset --hard` but vundler maintainer is afraid to do automatically, and it is right.

https://github.com/VundleVim/Vundle.vim/pull/400
