### ISSUE TITLE
More resources of {pattern}

### ISSUE THREAD

**Issue by benoittgt** [albfan/ag.vim#59]
Hello

We need for me a little bit more ressources about the `{pattern}`. I don't if it's belongs to the readme or the doc.

For exemple how to search `let(:my_app` in my project ?

Cheers

**Comment by amerlyq** [comment]
Plugin only provides wrapper/UI for `ag`, no more. So see `ag` reference first. 
As for example -- maybe `Ag let\(:my_app` or `Ag 'let\(:my_app'` or `Ag -Q 'let(:my_app'`?
It's simply syntax of PCRE and its escaping. No concern with `ag.vim`?
Where is problem? I don't understand your proposition at all, sorry.

**Comment by benoittgt** [comment]
You're right. It is not something that should be related to `ag.vim` but only with `ag` so not here. Sorry for the noise.

**Comment by albfan** [comment]
Use a trick I do use: Open a new file `:new`, write your text to search, visual select it and search it `<Leader>ag`. After that search is included on history so you can reuse it from command line

**Comment by benoittgt** [comment]
Thanks for the tips.
