### ISSUE TITLE
Add: multiline matches note to readme and help

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#63]
Need to add notion, that multiline matches are represented by consequent oneline matches (both in qf and grp). Therefore multiline patterns are actually splitted on each newline. This from one side allows to navigate to any line of multiline match, but from another -- exaggerates distinction and breaks agSearch highlighting (because of linenumber in-between of them).

``` sh
vim -c 'AgGroup -C 2 ;\n ' -c 'only|set cole=0'
```

**Comment by albfan** [comment]
Maybe multiline pattern can be detected and change highlight pattern to include numbers before newline

**Comment by amerlyq** [comment]
But they _must not_ be included, I don't want them to match or be highlighted. We, of course, can write something like `;\n\ze\d\+:\d\+:\zs...`, but splitted highlighting simply don't work.
