### ISSUE TITLE
Embedded multisyntax -- filetype detection

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#64]
This one is truly solemn:

We can't detect filetype by its path only. We need to respect modelines, because most of text files on unix have no extension at all. 
- Loading files from disk to memory alredy was done by kernel, when ag searched their content, so we ignore this overload. 
- But filetype detection in vim triggered mostly by autocmd on opening/creating file, therefore we can't re-use this mechanics as it involves also triggering millions of other functions beside filetype detection, attached to those autocmds.
- Making and maintaining custom script to detect filetype is great overhead and code duplication. It will never be complete, repeats vim mechanics but in less efficient vimscript.

Therefore I don't have any untried ideas how to resolve it. Can you propose something to do?
If not,  we can abandon multiple filetype embedded syntax completely.

**Comment by albfan** [comment]
I need some intro about what usecases this would resolve and why external plugin is not the right way to manage this. Filetype detection seems far from expected features for ag.vim,

**Comment by amerlyq** [comment]
Yes, main reason why re-implementing filetype detection isn't right way is because it's already implemented and moreover it's not what expected from ag.vim.
Do you need reasons for what multiple embedded syntax would be useful when looking at matching results? Or something else?
