### ISSUE TITLE
Embedded syntax -- linenumber prefix interference

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#65]
Each line of matching ag results has `lin-` or `lin:col:` prefix, which takes part in embedded syntax matching (even being concealed), and therefore all syntax groups of that language, which use start-of-line `^` can't be matched at all.
- Possible mitigation: when read ag results into vim buffer -- split out linenumbers into separate array, and use values from that array, when pressing `<CR>` on matching results. 
- But then we completely lose the ability to see linenumbers, when `conceallevel=0`. 
- However we could insert and draw linenumbers again manually like it was done in `easymotion` or `vim-sneak`. 
- Complexity of such solution isn't nice, but at least it's complete and certainly possible.

Do you have ideas or could investigate more info? 
I couldn't google out something appropriate to force all embedded syntax to ignore linenumber or treat `^` as starting after linenumber, or skip fixed columns count...

**Comment by albfan** [comment]
conceal was supposed to exists to avoid loose info about line. Once implemented there was few times when I need to consult it, so parse results and split lines and linenumber info seems ok.

Maybe  is possible to replicate a syntax highlight with fixed positions and translate that after add linenumber info. This leads again with keep dict objects with info (highlight in this case) and apply it when neccesary.

We can start with this codebase

http://vim.wikia.com/wiki/VimTip857
http://www.vim.org/scripts/script.php?script_id=4168

**Comment by amerlyq** [comment]
These tips will not work, I already thoroughly studied them. 
Even implemented its resulting essence -- you can try it by `:AgFt <ft>` :)

As for storing currently loaded syntax into dict and then manually applying each rule separately -- it's inefficient and will be too slow on many searches, because of `execute "syn ..."`. Moreover it will be even more slow for multiple embedded syntax -- if it will be implemented -- simply by number of rules. But main problem is manual patterns transformation -- it's even near not that simple and straight, as it looks. Therefore this solution is suitable only for desparate situations:)

Main goal is to resolve contradiction -- syntax must be applied on buffer without linenumbers, but be showed on screen with them. Minimal tweaking of basic vim functionality is appreciated.

**Comment by amerlyq** [comment]
Also, there is wrong syntax highlighting for scanty constructions, but don't know if we can do something about it. Example:

``` viml
:Ag fun
:AgFt vim
file.vim|3 col 1| endfunction
```

Here `endfunction` has wrong synID -- but when this single word is placed in separate vim file -- it has appropriate synID from vimsyntax. Don't know bug it or what...

``` viml
echo synIDattr(synID(line("."), col("."), 1), "name")
```
