### ISSUE TITLE
Doc: section with abbreviations

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#67]
Need to add section for abbrevs (in help only, until commands names not stabilized).

There must be mentioned, that expansion works after any range specifiers (when I'll complete appropriate regex for #51) in the beginning of cmdline, but not directly after numbers (so `:3agg` and `:.,.+2ag` don't work).
It's consequences of `3` isn't in `iskeyword` list and treated as part of abbrev.
Therefore equivalents for `:3Ag`  are `:3 ag` or `:3:ag` (or even `:3 : :   ::   ag`).

We can't tweak cabbrev mechanics beside changing `iskeyword` -- which is bad as it's systemwide.
And there no sense to introduce own completion mechanics by overloading `cmap <Space>...` -- because scope of our plugin is lesser than system-wide and mapping may be already overloaded by another plugin (however we could use chain mappings, I would like to avoid it).

**Comment by albfan** [comment]
Agreed to mention on help. 

But aside from having lowercase version for commands, if cabbrev is a bad short replace on commands, then why use it? I rather prefer to duplicate code and offer short version (for advanced users) fully functional.

**Comment by amerlyq** [comment]
Hm, I wouldn't say it's unfunctional. You simply need to insert space after
number if specifying counter or range, and it's all.
And now nor counter, nor range weren't even used yet for functionality.
Beside that, it's the single way to use lower case commands. Plus it's
simple and built-in way.
Lets use it for more time to decide, if there necessity to fall back to
short commands like Agg and Aggf. Because currently I like that even if you
forgot what abbrev means, you can remember that after expansion. With short
commands we lose such descriptivity.
