### ISSUE TITLE
Propose: change <bang> meaning

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#68]
Currently `:Ag!` opens first result and `:AgGroup!` not allowed at all.
It's too wasteful to use `!` to control only opening of first result.
Beside that, I very rarely need to open first result at all. And when I really need it, I use it multiple searches in succession.
Therefore I would liked to use `:AgToggleOpenFirst` to control old behaviour and make <bang> free to use for filename filter (see next issue).

**Comment by albfan** [comment]
Yes, I didn't feel the neccesity to open first result after a search, and lije the idea of toggle commands to activate ag.vim behaviour
