### ISSUE TITLE
Fea: filtering of filenames [-G]

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#69]
I have two distinct usecases -- kernel sources and many subprojects under mercurial.
In first one I need to search in all beside several dirs: `-G '^(?:(?!/build/|/libs/|/tags$).)*$'`.
For second one -- only in several choosen dirs/files.
There is `agignore`, but it doesn't allow to 'unignore' -- for second usecase.
Moreover, list of choosen ones may change after each dozen of searches, so re-writing .agignore each time have no much sense.

I would like to introduce control over `-G` option:
- `:AgSetFilter[!] ....` -- sets value for `-G` option for all commands w/o or w/ bang.
- `:AgSetIgnore[!] ....` -- sets value for `--ignore` option for all commands w/o or w/ bang.
- By default both filters are empty `g:ag.filter = ['', '']` ...
- To reset filter -- simply call w/o argument

Usecase (after we agreed on #68)
- `:AgSetFilter dir1|file1|file2` -- set filter for normal commands
- `:Ag ...' -- search in filtered
- `:Ag! ...' -- search normally
- `:AgSetFilter! dir2|file3` -- set second filter
- `:Ag ...' -- search by 1st filter
- `:Ag! ...' -- search by 2nd filter
- `:AgSetFilter` -- reset first filter to use again all files

**Comment by amerlyq** [comment]
By the way, I think I would also liked similarly made `:AgSetPaths[!] ...`.
That way we could eliminate arguments after pattern and treat whole cmdline as pattern for Ag and AgGroup. Therefore no need to use quotes, escape spaces, etc, etc. Searching anything from cmdline becomes nice. Moreover, we can introduce AgQ and AgGroupQ (or abbrev agq and aggq) and search for word sequence literally.

**Comment by albfan** [comment]
All this related to postprocess searchs and I am totally expectant to see this working.

My thoughs are this should be an implementation of an avaliable extension point for ag.vim, where others can implement and evolve ag.vim for particular cases not able to be managed from ag.vim plugin

**Comment by amerlyq** [comment]
I can't figure out currently cutting points for this feature, so let's
implement it to find them, and only then extract it as extension, if it
will be possible of course.

However, I don't understand why you call it postprocessing, because
applying of -G takes place before search -- in arguments construction phase.

**Comment by albfan** [comment]
It happens during first search on ag.vim, but since user didn't type it directly acts like a postprocess

-user write something
-filters change that search (truly speaking can be a preprocess too)
-results are shown

Ok to regine it after first implementation

**Comment by amerlyq** [comment]
If filters involve re-executing of ag with some arguments changed, I
wouldn't call it pre-/postprocessing at all. Isn't it simply repeating
search with state changed?

In my opinion postprocessing is applied to results and results only -- by
vimscript abilities -- like cleaning preview buffer from results you don't
like on second glance.

**Comment by amerlyq** [comment]
In prototype implementation we will have two distinct options set -- with and without `[!]`.
They are controllable independently with `:AgSet...[!]`.
Then I would suggest to use it to re-implement previous behaviour as #68  -- we introduce command `:AgToggleOpenFirst[!]` which will allow separately control that behaviour. Then, by activating 'open_first' for `!` set, we will receive exactly old behaviour.

All this toggling concept with distinct option sets introduces new possible modules `autoload/ag/state.vim` and `autoload/ag/behaviour.vim`.
