### ISSUE TITLE
Api: alternatives to specify -Q and -w on cmdline

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#70]
Alright, we won't use raw options before pattern.
Or even decline using filenames after pattern (see #69) at the end.
It allows us to treat whole cmdline as pattern. Good.
But how to specify `-Q` and `-w`?
Suppose `-w` we could replace by '\k...\k`, however it can be cumbersome.
What to do with`-Q`? 
Is there better way than introducing duplicated commands like`Ag...Q`?
What we yet not used from vim commandline UI, what could be useful?

**Comment by albfan** [comment]
I see all this stuff as something to activate with global options to change behaviour. If you add to .vimrc you set it at start, if not you activate during your session.

I like the idea to add commands to manage this options.

**Comment by amerlyq** [comment]
I don't know if permanent setter (option) has much sense. More often
decision which way to search is made depending on pattern and concrete case
- and it can be changed more often than you would liked to toggle that
  option. It's even more true for -w, which I use much rarely then -Q -
  because there is \k and I need to match word only on one side more often,
  then on both.

However commands like AgGroupW also could be added if needed, I would liked
to think out way to duplicate only cabbrev, but not commands itself. So
writing aggw will transform into XXXAgGroupYYY reusing already existing
command.
