### ISSUE TITLE
Enh:  pipe buffers to AgBuffer/AgGroupBuffer instead of filenames list

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#71]
Related to #62. Must be implemented first to check conception, because #62 is much more general wish, when this concrete implementation for one command -- is absolute necessity.
Can't be implemented in terms of `paths.vim` providers.
Must be created: new `content` providers and way to interact with them.

**Comment by albfan** [comment]
Great idea. Let's see where it take us. I'm ok with q&d branch proposals if you have anything started. Don't care if it break other features as long as it shows new ideas
