### ISSUE TITLE
Doc: usage techniques

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#74]
You may complain that it's something to put in wiki, but I like whe all necessary info is available under fingertips -- even in offline. It must not be something overhelmingly excessive and complete, but some useful tricks, etc would be enough. We simply have too many commands and mappings and having smart way to utilize all their potential would be very representative.

Let's place in this issue usage and technique primer -- from simple to more complex ones, which will be included in bottommost section of help.

**Comment by albfan** [comment]
Maybe both places is right, but I do like the idea people can see how to use on vim help, I always miss it on powerful plugins
