### ISSUE TITLE
Bug: one single quote at -Q bound

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#76]
When searching by visual-selecting and its region starts or ends with single quote -- this single quote don't take part in pattern matching. Consider line `if exists('s:ag_mappings')`. If I visual select `'s:` or `s'` and press `<Leader>af` then there will be found excess entries.

**Comment by albfan** [comment]
Yes. I have been working on searches with escape quotes or escape double quotes, but didn't find an easy solution as `" \" "` and `" \\" "` must be distinguished. Here history can help to refine search, and it's my current approach for the bug

**Comment by amerlyq** [comment]
Seems like problem with quotes is deduced to `mode()` problem from #79.
Therefore it's duplicate.
