### ISSUE TITLE
Fea: state control with AgSet and AgToggle

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#78]
Core functionality to be able to implement #68 and #69.

Instead of individual commands for each changeable option, I introduced unified interfaces:
`:AgSet <opt> val...` and `:AgToggle <opt>...`. 
Both supports autocompletion on `<Tab>` and can be bound to specific mappings:

```
nnoremap <Leader>atf  :AgToggle foldempty folddelim<CR>
```

Therefore you can change even default cmdline arguments on the fly.

```
:AgSet prg ag --vimgrep -S --ignore build
```

**Comment by amerlyq** [comment]
Why you removed 'ready'? It's issue assigned to me, which I have opened only one moment before closing by already waiting commit so I marked it as "work is done, don't bother with issue". Or you suppose to use "ready" for another purpose?

**Comment by albfan** [comment]
After discuss is complete, tag as `ready` means someone can start working on it. After closing, ready shouldn't be a tag for issue. See it this way: if `ready` says it is `done`, what means `closed`? if this is done on a branch maybe a `done` tag should be added or better `ready to merge`.
