### ISSUE TITLE
Propose: one type of argument per command

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#80]
What you think about dropping support for mixed arguments (similar to #55)?
So we will not be able to use pattern + files list. 
And one command sets only one type of argument -- or pattern, or file list.
After all, vim isn't command line and we can build statemachine incrementally.

Proc:
- No need in quoting/escaping arguments, spaces, quotes, etc on command line at all -- whole cmdline treated as pattern -- big plus as for me.
- We can focus on specific distinct autocompletion for each command
- You can set filelist by command and all mappings will reuse that filelist -- also big plus (currently mappings search only from providers but we can't specify filelist for them).
- We can use two types of commands -- to only change option value (bang version `:AgSet!, :AgToggle!` as rarely used) or change option and do search immediately (version w/o bang, often useful -- sounds intriguing). -- Bang is more useful here than for filters from #69.

Cons:
- Need to type two commands to search new pattern on new file list -- minor -- rarely needed.
- You can forget about previously setted files, when trying to search in pwd and get only part of matches instead all (seems like we need indicator of filter activity like #60).

**Comment by albfan** [comment]
I didn't investigate deeply, but I think AgGroupFile is broken too.

Many times I use:

```
:AgGroup <whatever>
```

with results on docs, help files, readme, test files, so I like to have a simple way to filter results as with

```
:AgGroupFile src/*.c <whatever>
```

See here command has an _File to distinguish where it is a specific search with paths, so in general for non *File commands seems reasonable to disable other arguments than patterns, i.e, avoid using :Ag_ as wrapper of ag but as a real command.

These would be a big change, so if you want to implement it, open a different branch (no-paths or similar) and let's see if it is useful or not

**Comment by amerlyq** [comment]
Alright, I will do asap, as it could help to resolve many other issues much
easily.

**Comment by amerlyq** [comment]
Planned to implement such one-arg distribution:
- `<bang>` used to choose "set option and search (false)" or only "set option (true)"
  - There also need of variant "set option for one-time search" -- to not influence global state. 
    - Such options must be saved in `g:ag.last` and cleared before each new search.
    - Names for options -- same as in `g:ag` and they are attributes for concrete search.
    - Maybe, it's reasonable to use `:Ag!! <patt>` if I could distinct first bang from pattern.
  - Therefore all commands must pass through one point -- to implement decision module and centralized history (and maybe toggle argument quoting option).
- View cmds `Ag, AgGroup, AgList, AgFind` by default consume raw patterns as-is `<q-args>`:
  - Patterns with trailing spaces work as expected, by including trailing spaces in patterns
  - Problem: prefix spaces (between command and pattern) are all dropped
    - Escaping don't work, as pattern is raw
    - We need quotes to include those spaces
    - Quotes become ambiguous, with different meaning dependent on position
  - Provide option to toggle usage of quotes on patterns -- when they are really needed.
  - Better solution: use leading backslash to mark pattern beginning: `:Ag \   3spacesbefore`
  - For `AgList` utilizing `-l` and `AgFind` utilizing `-g` there no sense in `AgGroup` variant, therefore it's separated in their own view.
  - Completion from history of previously inputted patterns (from both mapping and cmds)
- `AgAdd` implemented as view, as it will populate any current view by additional results and therefore similar to view itself
  - In general it must respect last view type -- matches `Ag, LAg, AgGroup` or filelist `AgList, AgFind` and inherit options like `-l, -g` from them when used.
  - If you want mixed matches/paths results -- there must be explicit `AgFindAdd`, etc, but then inheriting will lost it's sense, so better to drop mixed support for time being.
- Direct commands like `Ag, AgGroup` better to implement as aliases of consequent calls to `AgView` and `AgRgx`
  - Therefore we provide shortcut aliases and examples to create them
  - And keep overall one-arg architecture for args specifying
- Paths cmds `AgPaths` setup sources list using `<q-args>`, it's alias for one of `AgSrc` variants.
  - Whole list of paths treated as one argument! 
  - It's used by `ag` as-is without additional escaping.
  - Such usage allows us to use shell globbing in filenames.
  - Quotes and escaping are carried as they are and parsed by shell only. So them works.
  - When used w/o `<bang>`, last View will be re-used to show matches
  - Alternatively: treat args as elements to push/pop in list under veil (like AgSetAdd)
- Source cmds `AgSrc` setup sources list from one of pre-defined variants (pwd, onelevel, buffers, vim-help, filelist,...) -- replacing such old explicit commands as `AgBuffer, AgHelp, etc`.
  - Completion from allowed list of functions (by reflection)
- Filter cmds `AgFilter` utilize `-G` option to choose only matching paths from `AgSrc` list.
  - Completion from history
- Possibly, `AgFromSearch` (`ag#args#slash`) can be described by completion only w/o explicit command? However, no, it will be too profound.
- Idea: if `last.pattern = type([])` -- then do search for each of them through `AgAdd` to populate whole list.
  - So, `AgAdd` must work in similar way -- and add patterns to previous `ag.last`
  - Thus it will allow to `AgRepeat` whole set of patterns, re-populating matches.
    - However, it would be convenient to choose -- repeat whole set (if `AgAdd` merges will all previous) or directly any single of previous, or even any of prev combined subsets.
  - Need to consider how to treat situation when some of patterns 'not found' -- to not interrupt searching, but notify user about which patterns wasn't found.
  - In comm! need to change to `-nargs=*`
  - But what to do if after several `AgAdd` you will want to drop some patterns? Try `AgRemove`?
  - Same must be applied to `g:ag.last.paths` -- by populating `AgAdd` for several groups.
  - When several variables are lists -- then populate matrix `path1: rgx1...rgxN, path2: ....`.
- `Ag*Q` unconditionally overrides value of `g:ag.last.literal`
  - Therefore by default both `Ag*` and `Ag*Q` will treat visual selection as literal
  - But if user toggle option `g:ag.toggle.literal_vsel = 0` only `Ag*Q` will be literal
  - Mappings behaviour similar to `Ag` -- therefore depends on `literal_vsel` value.
- `AgWord` or `AgWhole` repeats last search with `-w` option, also need `AgWordQ`
  - TODO: decide on `args` and `bang`
- `AgReset` to return values in `g:ag.last` in their default form
- `AgArg` to specify additional raw cmdline (may be faster then specifying by several commands?)
- `AgSet!` -- with bang -- forces re-exec after changing option value.
