### ISSUE TITLE
Ease local testing

### ISSUE THREAD

**Issue by albfan** [albfan/ag.vim#81]
There's a series of quirks which discourage using our test suite, I will enumerate some of thems, and correct as match as I can. Some are plain to see, some requires debate.
- [x] using `Leader` on test. 

As leader mappings happens only at startup, if you have 

```
    let mapleader = ","
```

you cannot launch vader inside vim an get same results as in test suite. That's annoying
- [ ] hard autocompletion for single test

because of `suite.sh` is not on t/ dir, is hard to autocomplete test files for single execution
- [ ] fixtures for single test

as test suite executes test in "sandbox" inside tests, referred dirs did not exist, so execution inside vim is hard. My manual approach is:

```
- create a sandbox `t/sandbox`
- copy fixtures cp t/grp-all t/sandbox/fixture    
```
- open vader file
  - cd into t/sandbox
  - execute `Vader`

Seems to match config for newbies, (adding the learning curve for Vader maybe too much)
- [ ] Startup, teardown on test

https://github.com/albfan/ag.vim/blob/master/t/grp-all.vader#L6
https://github.com/albfan/ag.vim/blob/master/t/grp-all.vader#L88

https://github.com/albfan/ag.vim/blob/master/t/ag-cmdline.vader#L9
https://github.com/albfan/ag.vim/blob/master/t/ag-cmdline.vader#L57

If test need that is another quirk for test suite (another difficulty to use it) If test are executing on sandbox it must provide all the environment neccesary.

**Comment by amerlyq** [comment]
So, all those troubles, because you got tired from using tmux?:)

"leader mappings happens only at startup"
- You are slightly wrong. After you do `let mapleader = ","` it affects all next mappings definitions.
- Use `exe "normal \<Plug>(ag-qf)"` in test suite. Don't be attached to actual mapping!

"hard autocompletion"
- `cd ag.vim/t; ../scripts/suite.sh <Tab>` -- filename autocompletion
- `cd ag.vim; ./scripts/sute.sh grp` -- glob matching
- What you find here difficult? 
- I will never agree to mix scripts with tests, when there are plenty of them.

"referred dirs did not exist"
- What is it? Don't understand. Full scenario please.
- How you think it's possible to launch tests without setted environment?

"Startup, teardown on test"
- Agree. Also don't like it.
- But I simply refactored its logic, and not changed it -- it was like that before me.
- If you have alternative ideas -- show them when in mood.

**Comment by albfan** [comment]
"hard autocompletion" `../scripts/suite.sh <Tab>` is a fix, but I really dislike it. I'm thinking on someone which confront this project for first time. Is hard it realizes that command line usage. I like all test stuff in its directory, but that can work by now.

About "Startup, teardown on test" I fix it for aggroup test adding `syntax on` on helper.vim. 

"referred dirs did not exist" You almost find a solution on other test you write. `cd fixture`, `cd ..` makes ag search on current dir making unnecessary to add search path as I did:

https://github.com/albfan/ag.vim/blob/master/t/grp-all.vader#L5

Allowing `AgGroup fuga` don't find false positives on template fixtures for test.

That didn't fix the problem that `:Vader` inside vim doesn't copy template fixtures so you cannot develop test without a little manual config. Don't know how to solve it.

**Comment by amerlyq** [comment]
"hard autocomletion"
- I simply thinked about TESTING section in help with those two ways to launch tests.
- Minimal knowledge of shell makes them obvious and not hard at all. Do you really understimate those who decided to improve vimscript plugins?
- But if you have better ideas how to make it more clean (but not messed up) -- propose.
- Madness: we can make all `*.vader` executable and add shebang `#!../scripts/suite.sh`:) It's maddness, but will work-out as is;))

"referred dirs did not exist"
- I almost found solution, but you dislike it for startup/teardown, however they are absolutely normal
- Yes, they were added to avoid your way of doing things, as I thinked about disallowing mixed arguments from start. And that was part of my request to you to refactor your `grp-all.vader`.
- Truly speaking, start/tear was temporary solution -- we can rework suite.sh/help.vim in such a way to remove those `cd <...>` completely. But I don't too sure if lauching :Vader directly in vim will work than. Need investigate.

I again persist on `\<Plug>` and you still didn't tell any about this.
I really-really dislike your way using `get(g:, "mapleader", "\\")` and want more stable tests, not firmly linked with actual default mappings.

**Comment by albfan** [comment]
A TESTING section and a README.md on t/ dir would be great. Maybe that's enough for all problems. 

Launch inside vim is hard to combine with an isolate test suite, so documenting seems also the solution.

About mapleader  is just one tricky way to create a test. Leave that as an example.

As this is not an important issue, and the way is clear I will close it

**Comment by albfan** [comment]
Seems like there's a lack of usability which makes test suite unusable.

I guess it can be solve easily. Our test suite must help to create and test new issues

I have added several options:
-  `-e` or `--edit` ot test suite to check and edit a test.
- `-s` or  `--save` to save fixture changes after executing on sandbox
- `-f` or `--full` to avoid run without all config that must be avoided on final test (so users feel comfortable with edit
- `-h` or `--help` for a brief look at test suite capabilities

I guess an option for create new test must be provided to. Something like `-t` or `--template` which ask for several boilerplate data (name, description, status: failed, skip) and creates all the stuff for new test.

Hope that way proposing new features or explain bugs would turn really easy.

**Comment by amerlyq** [comment]
Isn't it too early to introduce such script-tests tight coupling and
additional options, until someone beside us start creating tests? And I
won't be using it anyway -- their creation is the least of the problems.
See api/docs branches. Aren't you extinguishing non-existent fire?
