### ISSUE TITLE
rebase on master

### ISSUE THREAD

**Issue by albfan** [albfan/ag.vim#82]
I want to change actual master branch to newmaster branch. Did I ever mention I love to rebase?

Main difference is:

https://github.com/albfan/ag.vim/blob/newmaster/t/grp-all.vader#L71

which is the race condition hiding the test for empty searches. After some test, Vader workbench has a preview window (used in AgGroup) and next command edit renames preview window to that file, confusing test about if empty buffer search is open or not.

See on that branch failed test is needed until fix commit

https://github.com/albfan/ag.vim/commit/73aa6878d60715cd3f23bc088e2cf439c52ec7d1#diff-3524d172671fcd77ad2bc1d89c604817R3
https://github.com/albfan/ag.vim/commit/77d5a7dbf887e80647b45eda8c2b4ad62e77a736#diff-3524d172671fcd77ad2bc1d89c604817L3

If is not feasible to change master branch I can do on top of actual master, but TDD will not be respected (as in newmaster)

**Comment by amerlyq** [comment]
Sorry, can't catch your point. Therefore I'm against all of it until I understand its inevitability.
What I have understood:
- You have added code, which checks buffer if empty and closes it
- Then you introduced crotch into tests to mitigate bug related to this your previous code
- Now you want completely new master populated with crotches.

Of course it recalls the rejection.
If there would not be necessity to close window after empty search, would those problems exist at all?

**Comment by albfan** [comment]
These feature do exist after heavy changes on codebase. My fault to not cover it with a test. To show how this should have been done this rebase fix a wrong failed test about open an empty search and shows how a commit fix it. I can open a branch on prior commit to show you that AgGroup do that some time ago.

I find confusing to see an empty search

**Comment by amerlyq** [comment]
Aah, yes, yes.
But better than closing it after search, I would suggest to _not open_ it at all.
To accomplish that, we simply need to split `put=shell(...)` into two separate actions.

``` viml
let _ = shell(...) 
if empty(_) | return | en
vnew "(Edit)
put = _
```

How about this? Will this cover up all that forced problems?

**Comment by amerlyq** [comment]
Also, I still don't understand point of newmaster? (Edit)
Why you would ever need that now?

**Comment by albfan** [comment]
Because this should be a failed test

https://github.com/albfan/ag.vim/commit/7b469e0dadca5838c53070c02d0e7d8a3935fe22

But, let's forget it. I check it and old version do not close empty searches, and now is covered. I was wrong.
