### ISSUE TITLE
Fix: ignore (drop) empty search from qf history

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#83]
We must not populate qf by matches if there is no one.
Because if do, we will be using history in unoptimal way.
Therefore -- we need to store results in variable and populate from it.
Related to #82

**Comment by albfan** [comment]
There's a commit to close empty searchs on aggroup. By now that works but I suppose there will be some flickering on large searches. Now buffer is open and later seaech is executed, we need to change that too.

**Comment by amerlyq** [comment]
I currently changed open-close behaviour to next:
- closed + no matches -- don't open
- closed + matches -- open
- opened + matches -- repopulate buffer with new matches
- opened + no matches -- do nothing (keep old matches for previous pattern)

So, if after some time you will have desire to restore old behaviour, we discuss that then. It was:
- opened + no matches -- close window

**Comment by amerlyq** [comment]
Maybe, for your case of `AgGroup` there is sense to check if window was already opened and setted up, and simply delete all lines and re-put new stuff. Currently there are some mess of it. If you feel lucky, create such issue on tracker to resolve.
