### ISSUE TITLE
Fix: when AgToggle highlight -- call function to toggle it

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#84]
Do as described.
Currently only option value changed, but it has no effect on current results.
Therefore we need to call actual function.
Task may be more deep and complex than seen.

**Comment by albfan** [comment]
Just add a handler. It wil link a variable with a function. Here ag highlight variable with a function detecting openened ag search buffer or qf and invoking toggle highlight in that case

**Comment by amerlyq** [comment]
Handler? Are there existing properties in vim? Or setter/getter hack?
I need precisely emulate setter to fuse properties with options under one interface.
Don't understand point of last sentence though :(

**Comment by amerlyq** [comment]
Alright, let stop at `anonymous-function` bay.
It's not what I would liked, but it's better then nothing nevertheless.
