### ISSUE TITLE
Add multiple directory when using ag with :exe

### ISSUE THREAD

**Issue by benoittgt** [albfan/ag.vim#99]
Hello

I was using the rking version but decided to switch to the updated version but in my vimrc I have : 
```viml
" Search with Ag word under cursor file under app and lib folders
nnoremap <leader>k :exe 'Ag!' expand('<cword>') 'app lib'<cr>
```
That no longer working with this ag.vim version.  It seems expression are link together. If I search the word "shop" it will search for "shop app lib".

Do you have any idea of what can I do to filter to folder(I use `ag 1.0.2`)?

Thanks

**Comment by benoittgt** [comment]
Stale issue. Closing for now.

**Comment by albfan** [comment]
I wasn't aware of this issue. Yes, this fork helps to search multiword easily, so this needs a new `:Agd` or similar to avoid that (and take rest of parameters as dirs to search). Usually I filter unwanted dirs with `:AgFilter`
